export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: string;
}

export const tools: Tool[] = [
  {
    slug: "qr-code",
    name: "QRコード作成",
    description: "テキストやURLからQRコードを簡単に作成。PNG画像としてダウンロードできます。",
    icon: "📱",
    category: "画像・メディア",
  },
  {
    slug: "character-count",
    name: "文字数カウント",
    description: "文章の文字数・単語数・行数をリアルタイムでカウント。レポートやSNS投稿に便利。",
    icon: "🔢",
    category: "テキスト",
  },
  {
    slug: "password-generator",
    name: "パスワード生成",
    description: "安全なランダムパスワードを生成。長さや使用文字を自由にカスタマイズ。",
    icon: "🔐",
    category: "セキュリティ",
  },
  {
    slug: "json-formatter",
    name: "JSON整形",
    description: "JSONデータを見やすくフォーマット。構文チェックも同時に行います。",
    icon: "📋",
    category: "開発ツール",
  },
  {
    slug: "color-converter",
    name: "カラーコード変換",
    description: "HEX・RGB・HSLのカラーコードを相互変換。プレビュー付きで色を確認。",
    icon: "🎨",
    category: "デザイン",
  },
  {
    slug: "base64",
    name: "Base64変換",
    description: "テキストをBase64にエンコード・デコード。日本語テキストにも対応。",
    icon: "🔄",
    category: "開発ツール",
  },
  {
    slug: "url-encode",
    name: "URLエンコード/デコード",
    description: "URLの日本語や特殊文字をパーセントエンコーディング形式に変換・復元。",
    icon: "🔗",
    category: "開発ツール",
  },
  {
    slug: "date-calculator",
    name: "日数計算",
    description: "2つの日付間の日数を計算。何日後・何日前の日付も求められます。",
    icon: "📅",
    category: "日常ツール",
  },
  {
    slug: "text-diff",
    name: "テキスト差分比較",
    description: "2つのテキストを比較して差分をハイライト表示。変更箇所を素早く確認。",
    icon: "📝",
    category: "テキスト",
  },
  {
    slug: "hash-generator",
    name: "ハッシュ生成",
    description: "SHA-1/SHA-256/SHA-512のハッシュ値を生成。データ整合性の確認に。",
    icon: "🛡️",
    category: "セキュリティ",
  },
  {
    slug: "fullwidth-halfwidth",
    name: "全角半角変換",
    description: "全角⇔半角の英数字変換、ひらがな⇔カタカナ変換に対応。",
    icon: "🔠",
    category: "テキスト",
  },
  {
    slug: "age-calculator",
    name: "年齢計算",
    description: "生年月日から年齢・生まれてからの日数・次の誕生日までを計算。",
    icon: "🎂",
    category: "日常ツール",
  },
  {
    slug: "unit-converter",
    name: "単位変換",
    description: "長さ・重さ・温度の単位を相互変換。cm/inch/kg/lbなど対応。",
    icon: "📏",
    category: "日常ツール",
  },
  {
    slug: "markdown-preview",
    name: "マークダウンプレビュー",
    description: "マークダウン記法をリアルタイムでHTMLプレビュー表示。",
    icon: "✍️",
    category: "開発ツール",
  },
  {
    slug: "html-escape",
    name: "HTMLエスケープ",
    description: "HTMLの特殊文字をエスケープ・アンエスケープ。XSS対策に。",
    icon: "🏷️",
    category: "開発ツール",
  },
  {
    slug: "csv-json",
    name: "CSV⇔JSON変換",
    description: "CSVデータをJSON形式に、JSONをCSV形式に相互変換。",
    icon: "📊",
    category: "開発ツール",
  },
  {
    slug: "regex-tester",
    name: "正規表現テスト",
    description: "正規表現パターンをリアルタイムでテスト。マッチ結果を即確認。",
    icon: "🔍",
    category: "開発ツール",
  },
  {
    slug: "text-replace",
    name: "テキスト置換",
    description: "テキスト内の文字列を一括検索・置換。正規表現にも対応。",
    icon: "🔃",
    category: "テキスト",
  },
  {
    slug: "dummy-text",
    name: "ダミーテキスト生成",
    description: "Webデザイン・モックアップ用の日本語ダミーテキストを生成。",
    icon: "📄",
    category: "テキスト",
  },
  {
    slug: "radix-converter",
    name: "進数変換",
    description: "2進数・8進数・10進数・16進数を相互変換。",
    icon: "🔢",
    category: "開発ツール",
  },
  {
    slug: "timestamp-converter",
    name: "タイムスタンプ変換",
    description: "Unixタイムスタンプと日時を相互変換。現在時刻も表示。",
    icon: "⏱️",
    category: "開発ツール",
  },
  {
    slug: "aspect-ratio",
    name: "アスペクト比計算",
    description: "画面の幅と高さからアスペクト比を計算。動画・画像サイズに。",
    icon: "🖥️",
    category: "デザイン",
  },
  {
    slug: "case-converter",
    name: "大文字小文字変換",
    description: "UPPER/lower/Title/camelCase/snake_case/kebab-caseに変換。",
    icon: "🔤",
    category: "テキスト",
  },
  {
    slug: "uuid-generator",
    name: "UUID生成",
    description: "ランダムなUUID（v4）を一括生成。最大100個まで。",
    icon: "🆔",
    category: "開発ツール",
  },
  {
    slug: "bmi-calculator",
    name: "BMI計算",
    description: "身長と体重からBMI（体格指数）を計算。肥満度を判定。",
    icon: "⚖️",
    category: "日常ツール",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum生成",
    description: "英語のLorem Ipsumダミーテキストを段落数指定で生成。",
    icon: "📜",
    category: "テキスト",
  },
  {
    slug: "reading-time",
    name: "読了時間計算",
    description: "文章の読了時間を推定。日本語・英語の両方に対応。",
    icon: "⏳",
    category: "テキスト",
  },
  {
    slug: "mortgage-calculator",
    name: "住宅ローン計算",
    description: "借入額・金利・年数から月々の返済額と総返済額を計算。",
    icon: "🏠",
    category: "日常ツール",
  },
  {
    slug: "ip-info",
    name: "IPアドレス確認",
    description: "自分のIPアドレス・端末情報・ブラウザ情報を確認。",
    icon: "🌐",
    category: "開発ツール",
  },
  {
    slug: "word-counter-en",
    name: "英語ワードカウンター",
    description: "英文の単語数・文数・段落数を計測。頻出単語も表示。",
    icon: "🔠",
    category: "テキスト",
  },
  {
    slug: "tax-calculator",
    name: "消費税計算",
    description: "税込・税抜価格を簡単計算。軽減税率8%にも対応。",
    icon: "🧾",
    category: "日常ツール",
  },
  {
    slug: "discount-calculator",
    name: "割引計算",
    description: "割引額・割引率を計算。セール価格の確認に便利。",
    icon: "🏷️",
    category: "日常ツール",
  },
  {
    slug: "random-number",
    name: "乱数生成",
    description: "指定範囲のランダムな数字を生成。複数同時生成も可能。",
    icon: "🎲",
    category: "日常ツール",
  },
  {
    slug: "text-sort",
    name: "テキスト行ソート",
    description: "テキストの行を昇順・降順・数値順に並べ替え。",
    icon: "📶",
    category: "テキスト",
  },
  {
    slug: "duplicate-remover",
    name: "重複行削除",
    description: "テキストの重複行を除去。大文字小文字の区別も選択可能。",
    icon: "🗑️",
    category: "テキスト",
  },
  {
    slug: "wareki-converter",
    name: "和暦西暦変換",
    description: "令和・平成・昭和・大正・明治を西暦に相互変換。",
    icon: "🗓️",
    category: "日常ツール",
  },
  {
    slug: "world-clock",
    name: "世界時計",
    description: "世界各地の現在時刻をリアルタイムで表示。時差確認に。",
    icon: "🕐",
    category: "日常ツール",
  },
  {
    slug: "number-formatter",
    name: "数字フォーマット",
    description: "数値をカンマ区切り・漢数字（万/億）・通貨形式に変換。",
    icon: "💹",
    category: "日常ツール",
  },
  {
    slug: "lottery",
    name: "抽選ツール",
    description: "リストからランダムに当選者を選出。抽選アニメーション付き。",
    icon: "🎯",
    category: "日常ツール",
  },
  {
    slug: "text-reverse",
    name: "テキスト反転",
    description: "文字列・単語・行の順序を反転。3つのモードに対応。",
    icon: "🔁",
    category: "テキスト",
  },
  {
    slug: "json-yaml",
    name: "JSON⇔YAML変換",
    description: "JSONとYAMLを相互変換。設定ファイルの形式変更に。",
    icon: "📑",
    category: "開発ツール",
  },
  {
    slug: "cron-parser",
    name: "Cron式解説",
    description: "Cronスケジュールを日本語で解説。次回実行時刻も表示。",
    icon: "⏰",
    category: "開発ツール",
  },
  {
    slug: "byte-counter",
    name: "バイト数計算",
    description: "テキストのバイト数をUTF-8/UTF-16等で計測。",
    icon: "📐",
    category: "開発ツール",
  },
  {
    slug: "color-names",
    name: "HTMLカラー名一覧",
    description: "CSS/HTMLカラー名とコードを検索。127色対応。",
    icon: "🌈",
    category: "デザイン",
  },
  {
    slug: "calculator",
    name: "電卓",
    description: "オンライン計算機。四則演算・パーセント計算に対応。",
    icon: "🔢",
    category: "日常ツール",
  },
  {
    slug: "percentage-calculator",
    name: "パーセント計算",
    description: "割合・百分率を3つのモードで計算。増減率にも対応。",
    icon: "📊",
    category: "日常ツール",
  },
  {
    slug: "countdown",
    name: "カウントダウン",
    description: "目標日までの残り時間をリアルタイムで表示。",
    icon: "⏳",
    category: "日常ツール",
  },
  {
    slug: "text-encrypt",
    name: "テキスト暗号化",
    description: "ROT13・シーザー暗号・XORで簡易暗号化・復号化。",
    icon: "🔒",
    category: "セキュリティ",
  },
  {
    slug: "image-resize",
    name: "画像リサイズ",
    description: "画像のサイズを変更。アスペクト比維持・形式変換対応。",
    icon: "🖼️",
    category: "画像・メディア",
  },
  {
    slug: "qr-reader",
    name: "画像情報確認",
    description: "画像のサイズ・形式・ファイルサイズを確認。",
    icon: "📷",
    category: "画像・メディア",
  },
];

export const siteConfig = {
  name: "ネットツールボックス",
  description: "無料で使えるWeb便利ツール集。QRコード作成、文字数カウント、パスワード生成など、日常で使えるツールが揃っています。",
  url: "https://net-toolbox.jp",
};
