export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: string;
}

export const tools: Tool[] = [
  {
    slug: "qr-code",
    name: "QRコード作成",
    description: "テキストやURLからQRコードを簡単に作成。PNG画像としてダウンロードできます。",
    icon: "📱",
    category: "画像・メディア",
  },
  {
    slug: "character-count",
    name: "文字数カウント",
    description: "文章の文字数・単語数・行数をリアルタイムでカウント。レポートやSNS投稿に便利。",
    icon: "🔢",
    category: "テキスト",
  },
  {
    slug: "password-generator",
    name: "パスワード生成",
    description: "安全なランダムパスワードを生成。長さや使用文字を自由にカスタマイズ。",
    icon: "🔐",
    category: "セキュリティ",
  },
  {
    slug: "json-formatter",
    name: "JSON整形",
    description: "JSONデータを見やすくフォーマット。構文チェックも同時に行います。",
    icon: "📋",
    category: "開発ツール",
  },
  {
    slug: "color-converter",
    name: "カラーコード変換",
    description: "HEX・RGB・HSLのカラーコードを相互変換。プレビュー付きで色を確認。",
    icon: "🎨",
    category: "デザイン",
  },
  {
    slug: "base64",
    name: "Base64変換",
    description: "テキストをBase64にエンコード・デコード。日本語テキストにも対応。",
    icon: "🔄",
    category: "開発ツール",
  },
  {
    slug: "url-encode",
    name: "URLエンコード/デコード",
    description: "URLの日本語や特殊文字をパーセントエンコーディング形式に変換・復元。",
    icon: "🔗",
    category: "開発ツール",
  },
  {
    slug: "date-calculator",
    name: "日数計算",
    description: "2つの日付間の日数を計算。何日後・何日前の日付も求められます。",
    icon: "📅",
    category: "日常ツール",
  },
  {
    slug: "text-diff",
    name: "テキスト差分比較",
    description: "2つのテキストを比較して差分をハイライト表示。変更箇所を素早く確認。",
    icon: "📝",
    category: "テキスト",
  },
  {
    slug: "hash-generator",
    name: "ハッシュ生成",
    description: "SHA-1/SHA-256/SHA-512のハッシュ値を生成。データ整合性の確認に。",
    icon: "🛡️",
    category: "セキュリティ",
  },
  {
    slug: "fullwidth-halfwidth",
    name: "全角半角変換",
    description: "全角⇔半角の英数字変換、ひらがな⇔カタカナ変換に対応。",
    icon: "🔠",
    category: "テキスト",
  },
  {
    slug: "age-calculator",
    name: "年齢計算",
    description: "生年月日から年齢・生まれてからの日数・次の誕生日までを計算。",
    icon: "🎂",
    category: "日常ツール",
  },
  {
    slug: "unit-converter",
    name: "単位変換",
    description: "長さ・重さ・温度の単位を相互変換。cm/inch/kg/lbなど対応。",
    icon: "📏",
    category: "日常ツール",
  },
  {
    slug: "markdown-preview",
    name: "マークダウンプレビュー",
    description: "マークダウン記法をリアルタイムでHTMLプレビュー表示。",
    icon: "✍️",
    category: "開発ツール",
  },
  {
    slug: "html-escape",
    name: "HTMLエスケープ",
    description: "HTMLの特殊文字をエスケープ・アンエスケープ。XSS対策に。",
    icon: "🏷️",
    category: "開発ツール",
  },
  {
    slug: "csv-json",
    name: "CSV⇔JSON変換",
    description: "CSVデータをJSON形式に、JSONをCSV形式に相互変換。",
    icon: "📊",
    category: "開発ツール",
  },
  {
    slug: "regex-tester",
    name: "正規表現テスト",
    description: "正規表現パターンをリアルタイムでテスト。マッチ結果を即確認。",
    icon: "🔍",
    category: "開発ツール",
  },
  {
    slug: "text-replace",
    name: "テキスト置換",
    description: "テキスト内の文字列を一括検索・置換。正規表現にも対応。",
    icon: "🔃",
    category: "テキスト",
  },
  {
    slug: "dummy-text",
    name: "ダミーテキスト生成",
    description: "Webデザイン・モックアップ用の日本語ダミーテキストを生成。",
    icon: "📄",
    category: "テキスト",
  },
  {
    slug: "radix-converter",
    name: "進数変換",
    description: "2進数・8進数・10進数・16進数を相互変換。",
    icon: "🔢",
    category: "開発ツール",
  },
  {
    slug: "timestamp-converter",
    name: "タイムスタンプ変換",
    description: "Unixタイムスタンプと日時を相互変換。現在時刻も表示。",
    icon: "⏱️",
    category: "開発ツール",
  },
  {
    slug: "aspect-ratio",
    name: "アスペクト比計算",
    description: "画面の幅と高さからアスペクト比を計算。動画・画像サイズに。",
    icon: "🖥️",
    category: "デザイン",
  },
  {
    slug: "case-converter",
    name: "大文字小文字変換",
    description: "UPPER/lower/Title/camelCase/snake_case/kebab-caseに変換。",
    icon: "🔤",
    category: "テキスト",
  },
  {
    slug: "uuid-generator",
    name: "UUID生成",
    description: "ランダムなUUID（v4）を一括生成。最大100個まで。",
    icon: "🆔",
    category: "開発ツール",
  },
  {
    slug: "bmi-calculator",
    name: "BMI計算",
    description: "身長と体重からBMI（体格指数）を計算。肥満度を判定。",
    icon: "⚖️",
    category: "日常ツール",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum生成",
    description: "英語のLorem Ipsumダミーテキストを段落数指定で生成。",
    icon: "📜",
    category: "テキスト",
  },
  {
    slug: "reading-time",
    name: "読了時間計算",
    description: "文章の読了時間を推定。日本語・英語の両方に対応。",
    icon: "⏳",
    category: "テキスト",
  },
  {
    slug: "mortgage-calculator",
    name: "住宅ローン計算",
    description: "借入額・金利・年数から月々の返済額と総返済額を計算。",
    icon: "🏠",
    category: "日常ツール",
  },
  {
    slug: "ip-info",
    name: "IPアドレス確認",
    description: "自分のIPアドレス・端末情報・ブラウザ情報を確認。",
    icon: "🌐",
    category: "開発ツール",
  },
  {
    slug: "word-counter-en",
    name: "英語ワードカウンター",
    description: "英文の単語数・文数・段落数を計測。頻出単語も表示。",
    icon: "🔠",
    category: "テキスト",
  },
  {
    slug: "tax-calculator",
    name: "消費税計算",
    description: "税込・税抜価格を簡単計算。軽減税率8%にも対応。",
    icon: "🧾",
    category: "日常ツール",
  },
  {
    slug: "discount-calculator",
    name: "割引計算",
    description: "割引額・割引率を計算。セール価格の確認に便利。",
    icon: "🏷️",
    category: "日常ツール",
  },
  {
    slug: "random-number",
    name: "乱数生成",
    description: "指定範囲のランダムな数字を生成。複数同時生成も可能。",
    icon: "🎲",
    category: "日常ツール",
  },
  {
    slug: "text-sort",
    name: "テキスト行ソート",
    description: "テキストの行を昇順・降順・数値順に並べ替え。",
    icon: "📶",
    category: "テキスト",
  },
  {
    slug: "duplicate-remover",
    name: "重複行削除",
    description: "テキストの重複行を除去。大文字小文字の区別も選択可能。",
    icon: "🗑️",
    category: "テキスト",
  },
  {
    slug: "wareki-converter",
    name: "和暦西暦変換",
    description: "令和・平成・昭和・大正・明治を西暦に相互変換。",
    icon: "🗓️",
    category: "日常ツール",
  },
  {
    slug: "world-clock",
    name: "世界時計",
    description: "世界各地の現在時刻をリアルタイムで表示。時差確認に。",
    icon: "🕐",
    category: "日常ツール",
  },
  {
    slug: "number-formatter",
    name: "数字フォーマット",
    description: "数値をカンマ区切り・漢数字（万/億）・通貨形式に変換。",
    icon: "💹",
    category: "日常ツール",
  },
  {
    slug: "lottery",
    name: "抽選ツール",
    description: "リストからランダムに当選者を選出。抽選アニメーション付き。",
    icon: "🎯",
    category: "日常ツール",
  },
  {
    slug: "text-reverse",
    name: "テキスト反転",
    description: "文字列・単語・行の順序を反転。3つのモードに対応。",
    icon: "🔁",
    category: "テキスト",
  },
  {
    slug: "json-yaml",
    name: "JSON⇔YAML変換",
    description: "JSONとYAMLを相互変換。設定ファイルの形式変更に。",
    icon: "📑",
    category: "開発ツール",
  },
  {
    slug: "cron-parser",
    name: "Cron式解説",
    description: "Cronスケジュールを日本語で解説。次回実行時刻も表示。",
    icon: "⏰",
    category: "開発ツール",
  },
  {
    slug: "byte-counter",
    name: "バイト数計算",
    description: "テキストのバイト数をUTF-8/UTF-16等で計測。",
    icon: "📐",
    category: "開発ツール",
  },
  {
    slug: "color-names",
    name: "HTMLカラー名一覧",
    description: "CSS/HTMLカラー名とコードを検索。127色対応。",
    icon: "🌈",
    category: "デザイン",
  },
  {
    slug: "calculator",
    name: "電卓",
    description: "オンライン計算機。四則演算・パーセント計算に対応。",
    icon: "🔢",
    category: "日常ツール",
  },
  {
    slug: "percentage-calculator",
    name: "パーセント計算",
    description: "割合・百分率を3つのモードで計算。増減率にも対応。",
    icon: "📊",
    category: "日常ツール",
  },
  {
    slug: "countdown",
    name: "カウントダウン",
    description: "目標日までの残り時間をリアルタイムで表示。",
    icon: "⏳",
    category: "日常ツール",
  },
  {
    slug: "text-encrypt",
    name: "テキスト暗号化",
    description: "ROT13・シーザー暗号・XORで簡易暗号化・復号化。",
    icon: "🔒",
    category: "セキュリティ",
  },
  {
    slug: "image-resize",
    name: "画像リサイズ",
    description: "画像のサイズを変更。アスペクト比維持・形式変換対応。",
    icon: "🖼️",
    category: "画像・メディア",
  },
  {
    slug: "qr-reader",
    name: "画像情報確認",
    description: "画像のサイズ・形式・ファイルサイズを確認。",
    icon: "📷",
    category: "画像・メディア",
  },
  { slug: "weekday-calculator", name: "曜日計算", description: "特定の日付の曜日を調べる。和暦表示にも対応。", icon: "📆", category: "日常ツール" },
  { slug: "zodiac-calculator", name: "干支計算", description: "生まれ年から十二支（干支）を調べる。", icon: "🐉", category: "日常ツール" },
  { slug: "horoscope-calculator", name: "星座計算", description: "誕生日から12星座を調べる。", icon: "⭐", category: "日常ツール" },
  { slug: "time-calculator", name: "時間計算", description: "時間の足し算・引き算。時分秒を計算。", icon: "⏱️", category: "日常ツール" },
  { slug: "speed-calculator", name: "速度計算", description: "距離・時間・速度を相互計算。", icon: "🚗", category: "日常ツール" },
  { slug: "electricity-calculator", name: "電気料金計算", description: "電化製品の月間・年間電気代を計算。", icon: "💡", category: "日常ツール" },
  { slug: "calorie-calculator", name: "基礎代謝計算", description: "年齢・性別・体格から1日の消費カロリーを計算。", icon: "🔥", category: "日常ツール" },
  { slug: "fuel-calculator", name: "燃費計算", description: "走行距離と給油量から燃費を計算。", icon: "⛽", category: "日常ツール" },
  { slug: "area-calculator", name: "面積計算", description: "円・長方形・三角形・台形の面積を計算。", icon: "📐", category: "日常ツール" },
  { slug: "volume-calculator", name: "体積計算", description: "直方体・球・円柱・円錐の体積を計算。", icon: "📦", category: "日常ツール" },
  { slug: "line-number", name: "行番号付与", description: "テキストの各行に行番号を追加。", icon: "🔢", category: "テキスト" },
  { slug: "html-strip", name: "HTMLタグ除去", description: "HTMLからタグを除去してテキストを抽出。", icon: "🧹", category: "テキスト" },
  { slug: "newline-converter", name: "改行コード変換", description: "CRLF/LF/CRの改行コードを相互変換。", icon: "↩️", category: "テキスト" },
  { slug: "indent-converter", name: "インデント変換", description: "タブ⇔スペースのインデントを変換。", icon: "➡️", category: "テキスト" },
  { slug: "text-similarity", name: "テキスト類似度", description: "2つの文章の類似度をパーセントで表示。", icon: "🔬", category: "テキスト" },
  { slug: "random-string", name: "ランダム文字列生成", description: "ランダムな文字列を指定条件で生成。", icon: "🎰", category: "開発ツール" },
  { slug: "char-code", name: "文字コード確認", description: "文字のUnicode・UTF-8コードを確認。", icon: "🔣", category: "開発ツール" },
  { slug: "unicode-search", name: "Unicode文字検索", description: "Unicode文字を名前やコードで検索・コピー。", icon: "🔎", category: "開発ツール" },
  { slug: "emoji-list", name: "絵文字一覧", description: "カテゴリ別の絵文字を検索・コピー。130種以上。", icon: "😀", category: "テキスト" },
  { slug: "text-binary", name: "テキスト⇔バイナリ", description: "文字列を2進数に変換・復元。", icon: "🔀", category: "開発ツール" },
  { slug: "sql-formatter", name: "SQLフォーマッター", description: "SQLクエリを見やすく整形。", icon: "🗃️", category: "開発ツール" },
  { slug: "css-formatter", name: "CSSフォーマッター", description: "CSSコードを見やすく整形・圧縮。", icon: "🎨", category: "開発ツール" },
  { slug: "xml-formatter", name: "XML整形", description: "XMLデータを見やすくフォーマット。", icon: "📰", category: "開発ツール" },
  { slug: "http-status-codes", name: "HTTPステータスコード一覧", description: "60以上のHTTPステータスコードを検索。", icon: "🌐", category: "開発ツール" },
  { slug: "keycode-checker", name: "キーコード確認", description: "キーボードのキーコードをリアルタイム表示。", icon: "⌨️", category: "開発ツール" },
  { slug: "useragent-parser", name: "UserAgent解析", description: "ブラウザ・OS・デバイス情報を解析。", icon: "🕵️", category: "開発ツール" },
  { slug: "css-unit-converter", name: "CSS単位変換", description: "px/rem/em/ptを相互変換。", icon: "📏", category: "開発ツール" },
  { slug: "css-gradient", name: "CSSグラデーション生成", description: "グラデーションCSSコードを視覚的に生成。", icon: "🌈", category: "デザイン" },
  { slug: "css-box-shadow", name: "CSSボックスシャドウ生成", description: "box-shadowをスライダーで視覚的に生成。", icon: "🖼️", category: "デザイン" },
  { slug: "htaccess-generator", name: ".htaccess生成", description: "リダイレクトやアクセス制御の.htaccessを生成。", icon: "⚙️", category: "開発ツール" },
  { slug: "random-color", name: "ランダムカラー生成", description: "ランダムな色をHEX/RGB/HSLで生成。", icon: "🎨", category: "デザイン" },
  { slug: "color-palette", name: "カラーパレット生成", description: "ベースカラーから配色パレットを自動生成。", icon: "🖌️", category: "デザイン" },
  { slug: "font-preview", name: "フォントプレビュー", description: "テキストを様々なフォントで比較プレビュー。", icon: "🔤", category: "デザイン" },
  { slug: "ogp-size-list", name: "OGP画像サイズ一覧", description: "SNS別のOGP推奨画像サイズを一覧表示。", icon: "📱", category: "デザイン" },
  { slug: "favicon-preview", name: "ファビコンプレビュー", description: "テキストや絵文字からファビコンをプレビュー。", icon: "🔖", category: "デザイン" },
  { slug: "barcode-generator", name: "バーコード生成", description: "テキストからCode128バーコードを生成。", icon: "📊", category: "画像・メディア" },
  { slug: "contrast-checker", name: "コントラスト比チェック", description: "WCAG基準で色のアクセシビリティを確認。", icon: "👁️", category: "デザイン" },
  { slug: "pixel-cm-converter", name: "ピクセル⇔cm変換", description: "DPI指定でpx/cm/mm/inchを相互変換。", icon: "📐", category: "デザイン" },
  { slug: "passphrase-generator", name: "パスフレーズ生成", description: "覚えやすい日本語パスフレーズを生成。", icon: "🔑", category: "セキュリティ" },
  { slug: "data-url", name: "データURL変換", description: "テキストをデータURI形式に変換。", icon: "🔗", category: "開発ツール" },
  { slug: "password-strength", name: "パスワード強度チェック", description: "パスワードの安全性をエントロピーで診断。", icon: "🛡️", category: "セキュリティ" },
  { slug: "port-list", name: "ポート番号一覧", description: "よく使われるTCP/UDPポート番号を検索。", icon: "🔌", category: "開発ツール" },
  { slug: "regex-cheatsheet", name: "正規表現チートシート", description: "正規表現の書き方をカテゴリ別に一覧表示。", icon: "📖", category: "開発ツール" },
  { slug: "keyboard-shortcuts", name: "ショートカットキー一覧", description: "Windows/Macのキーボードショートカット集。", icon: "⌨️", category: "開発ツール" },
  { slug: "sns-char-limit", name: "SNS文字数制限チェック", description: "各SNSの文字数制限をリアルタイム確認。", icon: "📱", category: "テキスト" },
  { slug: "sitemap-generator", name: "サイトマップ生成", description: "URLリストからXMLサイトマップを作成。", icon: "🗺️", category: "開発ツール" },
  { slug: "meta-tag-generator", name: "メタタグ生成", description: "SEO用メタタグ・OGPタグを自動生成。", icon: "🏷️", category: "開発ツール" },
  { slug: "robots-txt-generator", name: "robots.txt生成", description: "robots.txtをオプション選択で簡単作成。", icon: "🤖", category: "開発ツール" },
  { slug: "json-path-finder", name: "JSONパス検索", description: "JSONのキーをクリックしてパスを取得。", icon: "🔍", category: "開発ツール" },
  { slug: "markdown-table", name: "マークダウンテーブル生成", description: "表形式のデータからMarkdown表を作成。", icon: "📊", category: "開発ツール" },
  { slug: "compound-interest", name: "複利計算", description: "元金・金利・期間から複利で増える金額を計算。", icon: "💰", category: "日常ツール" },
  { slug: "savings-calculator", name: "積立計算", description: "毎月の積立額から将来の資産を計算。", icon: "🏦", category: "日常ツール" },
  { slug: "currency-converter", name: "為替換算", description: "主要通貨を日本円に換算。10通貨対応。", icon: "💱", category: "日常ツール" },
  { slug: "salary-calculator", name: "給与手取り計算", description: "年収から手取り額を概算。", icon: "💼", category: "日常ツール" },
  { slug: "split-bill", name: "割り勘計算", description: "合計金額と人数から一人あたりの支払額を計算。", icon: "🍻", category: "日常ツール" },
  { slug: "profit-calculator", name: "利益率計算", description: "売上と原価から利益率を計算。", icon: "📈", category: "日常ツール" },
  { slug: "roi-calculator", name: "ROI計算", description: "投資額と収益から投資収益率を計算。", icon: "📊", category: "日常ツール" },
  { slug: "breakeven-calculator", name: "損益分岐点計算", description: "固定費・変動費から損益分岐点を計算。", icon: "⚖️", category: "日常ツール" },
  { slug: "ideal-weight", name: "適正体重計算", description: "身長から適正体重を複数の計算式で算出。", icon: "🏃", category: "日常ツール" },
  { slug: "water-intake", name: "水分摂取量計算", description: "体重と活動量から1日の必要水分量を計算。", icon: "💧", category: "日常ツール" },
  { slug: "sleep-calculator", name: "睡眠時間計算", description: "起床時刻から理想の就寝時刻を計算。", icon: "😴", category: "日常ツール" },
  { slug: "dog-age-calculator", name: "犬の年齢計算", description: "犬の年齢を人間に換算。", icon: "🐕", category: "日常ツール" },
  { slug: "timer", name: "タイマー", description: "カウントダウンタイマー。アラーム付き。", icon: "⏲️", category: "日常ツール" },
  { slug: "stopwatch", name: "ストップウォッチ", description: "経過時間を計測。ラップタイム対応。", icon: "⏱️", category: "日常ツール" },
  { slug: "pomodoro-timer", name: "ポモドーロタイマー", description: "25分集中+5分休憩の作業タイマー。", icon: "🍅", category: "日常ツール" },
  { slug: "gcd-lcm", name: "最大公約数・最小公倍数", description: "2つ以上の数のGCD・LCMを計算。", icon: "🔢", category: "日常ツール" },
  { slug: "prime-checker", name: "素数判定", description: "数値が素数かどうかを判定。素因数分解も。", icon: "🔬", category: "日常ツール" },
  { slug: "factorial", name: "階乗計算", description: "階乗・順列・組み合わせを計算。", icon: "❗", category: "日常ツール" },
  { slug: "fibonacci", name: "フィボナッチ数列", description: "フィボナッチ数列を指定項数まで生成。", icon: "🌀", category: "日常ツール" },
  { slug: "trigonometry", name: "三角関数計算", description: "sin/cos/tan等の三角関数を計算。", icon: "📐", category: "日常ツール" },
  { slug: "logarithm", name: "対数計算", description: "常用対数・自然対数・任意底の対数を計算。", icon: "📈", category: "日常ツール" },
  { slug: "statistics", name: "統計計算", description: "平均・中央値・標準偏差等の統計値を計算。", icon: "📊", category: "日常ツール" },
  { slug: "probability", name: "確率計算", description: "順列・組み合わせ・確率を計算。", icon: "🎲", category: "日常ツール" },
  { slug: "vertical-text", name: "縦書き変換", description: "テキストを縦書き表示に変換。", icon: "📜", category: "テキスト" },
  { slug: "halfwidth-katakana", name: "半角カタカナ変換", description: "全角⇔半角カタカナを変換。濁点対応。", icon: "🔤", category: "テキスト" },
  { slug: "text-split", name: "テキスト分割", description: "区切り文字でテキストを分割。", icon: "✂️", category: "テキスト" },
  { slug: "csv-viewer", name: "CSVビューアー", description: "CSVデータを表形式で見やすく表示。", icon: "📋", category: "開発ツール" },
  { slug: "tsv-csv-converter", name: "TSV⇔CSV変換", description: "タブ区切り⇔カンマ区切りを変換。", icon: "🔄", category: "開発ツール" },
  { slug: "json-minify", name: "JSON圧縮", description: "JSONを最小化して容量を削減。", icon: "📦", category: "開発ツール" },
  { slug: "word-frequency", name: "単語頻度分析", description: "テキストの出現単語をランキング表示。", icon: "📊", category: "テキスト" },
  { slug: "css-animation", name: "CSSアニメーション生成", description: "CSSアニメーションを視覚的に生成。", icon: "🎬", category: "デザイン" },
  { slug: "css-flexbox", name: "CSS Flexbox", description: "Flexboxレイアウトを視覚的に確認。", icon: "📐", category: "デザイン" },
  { slug: "css-grid", name: "CSS Grid", description: "Gridレイアウトを視覚的に確認。", icon: "🔲", category: "デザイン" },
  { slug: "url-parser", name: "URLパーサー", description: "URLの構成要素を分解して表示。", icon: "🔗", category: "開発ツール" },
  { slug: "cookie-viewer", name: "Cookie確認", description: "ブラウザのCookieを一覧表示。", icon: "🍪", category: "開発ツール" },
  { slug: "localstorage-viewer", name: "LocalStorage確認", description: "ブラウザのLocalStorageを管理。", icon: "💾", category: "開発ツール" },
  { slug: "responsive-tester", name: "レスポンシブテスター", description: "各画面サイズでのサイト表示を確認。", icon: "📱", category: "開発ツール" },
  { slug: "image-base64", name: "画像Base64変換", description: "画像をBase64データURLに変換。", icon: "🖼️", category: "画像・メディア" },
  { slug: "screen-size", name: "画面サイズ確認", description: "画面・ウィンドウのサイズをリアルタイム表示。", icon: "🖥️", category: "開発ツール" },
  { slug: "video-size-calculator", name: "動画容量計算", description: "解像度・ビットレートから動画容量を見積もり。", icon: "🎥", category: "画像・メディア" },
  { slug: "audio-bitrate", name: "音声ビットレート計算", description: "音声ファイルの容量をビットレートから計算。", icon: "🎵", category: "画像・メディア" },
  { slug: "image-size-estimator", name: "画像容量見積もり", description: "画像のファイルサイズを解像度から推定。", icon: "📸", category: "画像・メディア" },
  { slug: "data-size-converter", name: "データ容量変換", description: "B/KB/MB/GB/TBを相互変換。", icon: "💿", category: "開発ツール" },
  { slug: "speed-unit-converter", name: "速度単位変換", description: "km/h・mph・m/s・ノットを変換。", icon: "🏎️", category: "日常ツール" },
  { slug: "angle-converter", name: "角度変換", description: "度・ラジアン・グラジアンを変換。", icon: "📐", category: "日常ツール" },
  { slug: "title-checker", name: "タイトルタグチェッカー", description: "SEOタイトルの長さとSERP表示を確認。", icon: "🏷️", category: "開発ツール" },
  { slug: "meta-description-checker", name: "メタディスクリプションチェッカー", description: "SEO説明文の長さをチェック。", icon: "📝", category: "開発ツール" },
  { slug: "keyword-density", name: "キーワード密度計算", description: "テキスト内のキーワード出現率を計算。", icon: "🔑", category: "開発ツール" },
  { slug: "heading-checker", name: "見出し構造チェッカー", description: "HTML見出しの階層構造を確認。", icon: "📑", category: "開発ツール" },
  { slug: "google-preview", name: "Google検索結果プレビュー", description: "SERPでの表示をプレビュー。", icon: "🔍", category: "開発ツール" },
  { slug: "og-preview", name: "OGPプレビュー", description: "SNSシェア時のOGP表示を確認。", icon: "📱", category: "開発ツール" },
  { slug: "twitter-preview", name: "Twitter Cardプレビュー", description: "X/Twitterでのカード表示を確認。", icon: "🐦", category: "開発ツール" },
  { slug: "jsonld-generator", name: "構造化データ生成", description: "JSON-LD構造化データを作成。", icon: "🏗️", category: "開発ツール" },
  { slug: "breadcrumb-generator", name: "パンくずリスト生成", description: "パンくずのHTML/JSON-LDを作成。", icon: "🍞", category: "開発ツール" },
  { slug: "gitignore-generator", name: ".gitignore生成", description: "言語別の.gitignoreファイルを作成。", icon: "📁", category: "開発ツール" },
  { slug: "readme-generator", name: "README生成", description: "README.mdテンプレートを作成。", icon: "📖", category: "開発ツール" },
  { slug: "license-generator", name: "ライセンス生成", description: "MIT/Apache/GPL等のライセンスを作成。", icon: "⚖️", category: "開発ツール" },
  { slug: "ip-converter", name: "IPアドレス変換", description: "IPを2進数・16進数・整数に変換。", icon: "🌐", category: "開発ツール" },
  { slug: "mac-formatter", name: "MACアドレスフォーマッター", description: "MACアドレスを各種形式に整形。", icon: "🔌", category: "開発ツール" },
  { slug: "jwt-decoder", name: "JWTデコーダー", description: "JWTトークンのヘッダー・ペイロードを解析。", icon: "🔓", category: "開発ツール" },
  { slug: "crontab-generator", name: "Crontab生成", description: "cronスケジュールを視覚的に作成。", icon: "⏰", category: "開発ツール" },
  { slug: "docker-template", name: "Dockerfileテンプレート", description: "Dockerfileを簡単に生成。", icon: "🐳", category: "開発ツール" },
  { slug: "random-name", name: "ランダム名前生成", description: "ダミーの日本人名を生成。", icon: "👤", category: "日常ツール" },
  { slug: "dice", name: "サイコロ", description: "オンラインダイスロール。多面体対応。", icon: "🎲", category: "日常ツール" },
  { slug: "janken", name: "じゃんけん", description: "コンピュータとじゃんけん対戦。", icon: "✊", category: "日常ツール" },
  { slug: "typing-test", name: "タイピング速度テスト", description: "タイピング速度を計測。", icon: "⌨️", category: "日常ツール" },
  { slug: "reaction-test", name: "反応速度テスト", description: "反応速度をミリ秒で計測。", icon: "⚡", category: "日常ツール" },
  { slug: "memory-test", name: "記憶力テスト", description: "数字の記憶力をテスト。", icon: "🧠", category: "日常ツール" },
  { slug: "notepad", name: "メモ帳", description: "ブラウザで使えるオンラインメモ帳。自動保存。", icon: "📝", category: "日常ツール" },
  { slug: "todo-list", name: "TODOリスト", description: "ブラウザで使えるタスク管理ツール。", icon: "✅", category: "日常ツール" },
  { slug: "checklist-generator", name: "チェックリスト生成", description: "チェックリストを作成・印刷。", icon: "☑️", category: "日常ツール" },
  { slug: "color-blindness", name: "色覚シミュレーション", description: "色覚異常での色の見え方を確認。", icon: "👁️", category: "デザイン" },
  { slug: "emoji-converter", name: "顔文字⇔絵文字変換", description: "顔文字と絵文字を相互変換。", icon: "😊", category: "テキスト" },
  { slug: "placeholder-image", name: "プレースホルダー画像", description: "ダミー画像URLを指定サイズで生成。", icon: "🖼️", category: "デザイン" },
  { slug: "gradient-text", name: "グラデーション文字", description: "グラデーション文字のCSSを生成。", icon: "🌈", category: "デザイン" },
  { slug: "border-radius", name: "border-radius生成", description: "角丸CSSを視覚的に生成。", icon: "⬜", category: "デザイン" },
  { slug: "text-to-speech", name: "テキスト読み上げ", description: "ブラウザでテキストを音声再生。", icon: "🔊", category: "日常ツール" },
  { slug: "aspect-ratio-list", name: "アスペクト比一覧", description: "よく使われる画面比率と解像度の一覧。", icon: "🖥️", category: "デザイン" },
  { slug: "encoding-detector", name: "文字化け修復", description: "文字化けしたテキストの修復を試みる。", icon: "🔧", category: "テキスト" },
  { slug: "what-day", name: "○日後計算", description: "指定日数後の日付を計算。", icon: "📅", category: "日常ツール" },
  { slug: "json-diff", name: "JSON差分比較", description: "2つのJSONの違いを比較。", icon: "🔍", category: "開発ツール" },
  { slug: "regex-generator", name: "正規表現パターン集", description: "よく使う正規表現パターンをコピー。", icon: "📋", category: "開発ツール" },
  { slug: "html-table", name: "HTMLテーブル生成", description: "HTML表を視覚的に作成。", icon: "📊", category: "開発ツール" },
  { slug: "char-diff", name: "文字レベル差分", description: "文字単位の差分をハイライト表示。", icon: "🔬", category: "テキスト" },
  { slug: "word-counter-jp", name: "日本語文字種カウンター", description: "漢字・ひらがな・カタカナの内訳を表示。", icon: "🔢", category: "テキスト" },
  { slug: "color-picker", name: "カラーピッカー", description: "HSLスライダーで直感的に色を選択。", icon: "🎨", category: "デザイン" },
  { slug: "whitespace-remover", name: "空白除去", description: "余分な空白・空行を一括削除。", icon: "🧹", category: "テキスト" },
  { slug: "number-to-kanji", name: "数字⇔漢数字変換", description: "数字を漢数字（一二三/壱弐参）に変換。", icon: "🔢", category: "日常ツール" },
  { slug: "epoch-converter", name: "エポック秒変換", description: "Unixエポックミリ秒⇔日時を変換。", icon: "⏰", category: "開発ツール" },
  { slug: "privacy-generator", name: "プライバシーポリシー生成", description: "個人情報保護方針テンプレートを作成。", icon: "🔒", category: "開発ツール" },
  { slug: "terms-generator", name: "利用規約生成", description: "利用規約テンプレートを作成。", icon: "📜", category: "開発ツール" },
  { slug: "slug-generator", name: "スラッグ生成", description: "URL用スラッグを自動生成。", icon: "🔗", category: "開発ツール" },
  { slug: "qr-bulk", name: "QRコード一括生成", description: "複数のQRコードを一度に生成。", icon: "📱", category: "画像・メディア" },
  { slug: "password-list", name: "パスワード一括生成", description: "複数のパスワードを一度に生成。", icon: "🔐", category: "セキュリティ" },
  { slug: "aspect-resizer", name: "アスペクト比リサイズ計算", description: "目標比率に合わせたサイズを計算。", icon: "📏", category: "デザイン" },
  { slug: "presentation-timer", name: "プレゼンタイマー", description: "プレゼンの残り時間を大画面表示。", icon: "🎤", category: "日常ツール" },
  { slug: "date-formatter", name: "日付フォーマット", description: "日付を10種類の形式で表示。", icon: "📅", category: "日常ツール" },
  { slug: "lorem-jp", name: "日本語ダミーテキスト（名文）", description: "名作文学からサンプル文を生成。", icon: "📚", category: "テキスト" },
  { slug: "cidr-calculator", name: "CIDRサブネット計算", description: "IPサブネットの範囲・ホスト数を計算。", icon: "🌐", category: "開発ツール" },
  { slug: "interview-timer", name: "面接タイマー", description: "面接の時間配分をステージ別に管理。", icon: "🤝", category: "日常ツール" },
  { slug: "ip-address", name: "IPアドレス確認", description: "現在のグローバルIPアドレスとユーザーエージェント情報を表示。", icon: "🌐", category: "開発ツール" },
  { slug: "http-status", name: "HTTPステータスコード一覧", description: "HTTPステータスコードの意味を検索・一覧表示。Web開発の参照に。", icon: "📡", category: "開発ツール" },
  { slug: "countdown-timer", name: "カウントダウンタイマー", description: "目標日時までの残り時間をリアルタイムで表示。", icon: "⏰", category: "日常ツール" },
  { slug: "image-compressor", name: "画像圧縮", description: "ブラウザ内で画像を圧縮・軽量化。サーバー送信なしで安心。", icon: "🗜️", category: "画像・メディア" },
  { slug: "favicon-generator", name: "ファビコン生成", description: "テキストや絵文字からファビコンを作成。色・形状カスタマイズ対応。", icon: "⭐", category: "デザイン" },
  { slug: "svg-to-png", name: "SVG→PNG変換", description: "SVGファイルやコードをPNG画像に変換してダウンロード。倍率・背景色指定対応。", icon: "🖼️", category: "画像・メディア" },
  { slug: "text-to-image", name: "テキスト画像生成", description: "テキストを画像化。フォント・色・サイズを自由にカスタマイズしてPNGダウンロード。", icon: "🅰️", category: "画像・メディア" },
  { slug: "box-shadow", name: "box-shadow生成", description: "CSSのbox-shadowをスライダーで視覚的に作成。複数シャドウ対応。", icon: "🎭", category: "デザイン" },
  { slug: "flexbox-generator", name: "Flexboxジェネレーター", description: "Flexboxのプロパティを視覚的に設定しCSSコードを自動生成。", icon: "📐", category: "デザイン" },
  { slug: "wifi-qr", name: "WiFi QRコード", description: "WiFiのSSIDとパスワードからQRコードを生成。スマホで読み取り接続。", icon: "📶", category: "日常ツール" },
  { slug: "text-repeat", name: "テキスト繰り返し", description: "テキストをN回繰り返して生成。テストデータ作成やダミーテキスト生成に。", icon: "🔁", category: "テキスト" },
  { slug: "url-encoder", name: "URLエンコード変換", description: "URLの特殊文字をencodeURIComponent/encodeURIでエンコード・デコード。", icon: "🔗", category: "開発ツール" },
  { slug: "image-crop", name: "画像切り抜き", description: "ブラウザ内で画像をトリミング・切り抜きしてダウンロード。サーバー送信不要。", icon: "✂️", category: "画像・メディア" },
  { slug: "typography-scale", name: "タイポグラフィスケール", description: "ベースサイズと比率からフォントサイズスケールを自動生成。", icon: "🔤", category: "デザイン" },
  { slug: "base-converter", name: "進数変換", description: "2進数・8進数・10進数・16進数を相互変換。プログラミング学習に。", icon: "🔢", category: "開発ツール" },
  { slug: "dns-lookup", name: "DNS情報確認", description: "ドメインのDNSレコード情報を確認。A/MX/NS/TXTレコード対応。", icon: "🌐", category: "開発ツール" },
  { slug: "instagram-font", name: "インスタフォント変換", description: "通常テキストをおしゃれな特殊文字・フォントに変換。インスタグラムのプロフィールや投稿に。", icon: "✨", category: "テキスト" },
  { slug: "ruby-generator", name: "ふりがなHTML生成", description: "漢字にふりがなを付けるrubyタグHTMLを自動生成。Webコンテンツのルビ振りに。", icon: "🔤", category: "テキスト" },
  { slug: "aspect-ratio-calculator", name: "アスペクト比計算機", description: "幅と高さからアスペクト比を計算。リサイズ時の寸法も自動計算。", icon: "📐", category: "画像・メディア" },
  { slug: "cron-generator", name: "Cron式ジェネレーター", description: "スケジュール実行のCron式を視覚的に作成。日本語で意味も表示。", icon: "🕐", category: "開発ツール" },
  { slug: "subnet-calculator", name: "サブネット計算機", description: "IPアドレスとサブネットマスクからネットワーク情報を計算。CIDR表記対応。", icon: "🔌", category: "開発ツール" },
  { slug: "reading-time", name: "読了時間計算", description: "文章を貼り付けると読み終わるまでの時間を推定。ブログ記事やプレゼン原稿の時間管理に。", icon: "📖", category: "テキスト" },
  { slug: "ogp-checker", name: "OGP確認ツール", description: "URLを入力するとOGPタグ（タイトル・説明・画像）を取得してプレビュー表示。", icon: "🔍", category: "開発ツール" },
  { slug: "mortgage-calculator", name: "住宅ローン計算", description: "借入額・金利・返済期間から毎月の返済額と総支払額をシミュレーション。", icon: "🏠", category: "日常ツール" },
  { slug: "tax-calculator", name: "消費税計算", description: "税込・税抜価格を即座に計算。8%・10%の軽減税率にも対応。", icon: "💴", category: "日常ツール" },
  { slug: "color-gradient-css", name: "CSSグラデーション生成", description: "方向・色数を選んでCSSグラデーションコードを生成。プレビュー付き。", icon: "🌈", category: "デザイン" },
  { slug: "screen-resolution", name: "画面解像度確認", description: "現在のブラウザ・画面の解像度やピクセル比をリアルタイム表示。", icon: "🖥️", category: "開発ツール" },
  { slug: "calorie-burn", name: "消費カロリー計算", description: "運動の種類と時間から消費カロリーを計算。ダイエット・健康管理に。", icon: "🏃", category: "日常ツール" },
  { slug: "json-to-typescript", name: "JSON→TypeScript変換", description: "JSONデータからTypeScriptの型定義を自動生成。APIレスポンスの型付けに。", icon: "📝", category: "開発ツール" },
  { slug: "emoji-search", name: "絵文字検索", description: "キーワードで絵文字を検索。クリックでコピー。SNS投稿やチャットに。", icon: "😀", category: "テキスト" },
  { slug: "rent-split", name: "割り勘計算", description: "金額と人数で均等割り、メンバー別の金額調整もできる割り勘ツール。", icon: "💰", category: "日常ツール" },
  { slug: "salary-calculator", name: "手取り計算", description: "年収・月収から手取り額を概算。社会保険料・所得税・住民税を自動計算。", icon: "💵", category: "日常ツール" },
  { slug: "loan-comparison", name: "ローン比較計算", description: "複数のローン条件を並べて比較。金利・期間による総支払額の違いが一目瞭然。", icon: "🏦", category: "日常ツール" },
  { slug: "sleep-calculator", name: "睡眠時間計算", description: "就寝・起床時間から最適な睡眠サイクルを計算。レム睡眠に合わせたアラーム設定に。", icon: "😴", category: "日常ツール" },
  { slug: "blood-type-calculator", name: "血液型予測", description: "両親の血液型から子供の血液型の確率を計算。遺伝の仕組みも解説。", icon: "🩸", category: "日常ツール" },
  { slug: "timezone-converter", name: "タイムゾーン変換", description: "世界各地のタイムゾーン間で時刻を変換。海外との会議時間調整に。", icon: "🌍", category: "日常ツール" },
  { slug: "json-to-csv", name: "JSON→CSV変換", description: "JSONデータをCSV形式に変換してダウンロード。データ加工・分析に。", icon: "📊", category: "開発ツール" },
  { slug: "html-to-markdown", name: "HTML→Markdown変換", description: "HTMLコードをMarkdown形式に変換。ブログ移行やドキュメント作成に。", icon: "📄", category: "開発ツール" },
  { slug: "css-minifier", name: "CSS圧縮", description: "CSSコードを圧縮・minify。空白やコメントを除去してファイルサイズを削減。", icon: "🗜️", category: "開発ツール" },
  { slug: "js-minifier", name: "JavaScript圧縮", description: "JavaScriptコードを圧縮・minify。ページ読み込み速度の改善に。", icon: "⚡", category: "開発ツール" },
  { slug: "sql-formatter", name: "SQL整形", description: "SQLクエリを見やすくフォーマット。複雑なクエリの可読性を向上。", icon: "🗃️", category: "開発ツール" },
  { slug: "chmod-calculator", name: "chmod計算機", description: "Linuxのファイルパーミッション（chmod）を数値⇔記号で相互変換。", icon: "🔧", category: "開発ツール" },
  { slug: "meta-tag-generator", name: "メタタグ生成", description: "SEO用メタタグ（title・description・OGP）をフォームから簡単生成。", icon: "🏷️", category: "開発ツール" },
  { slug: "twitter-card-preview", name: "Twitterカードプレビュー", description: "ブログ記事のTwitterカード表示をプレビュー。タイトル・画像の見え方を確認。", icon: "🐦", category: "開発ツール" },
  { slug: "image-to-base64", name: "画像→Base64変換", description: "画像ファイルをBase64文字列に変換。CSS埋め込みやメール添付に。", icon: "🖼️", category: "開発ツール" },
  { slug: "pixel-ruler", name: "ピクセル定規", description: "画面上のピクセル距離を計測。Webデザインのサイズ確認に。", icon: "📏", category: "デザイン" },
  { slug: "font-pairing", name: "フォント組み合わせ", description: "見出しと本文のフォントの組み合わせをプレビュー。Google Fonts対応。", icon: "🔠", category: "デザイン" },
  { slug: "svg-optimizer", name: "SVG最適化", description: "SVGコードの不要な属性を削除して最適化。ファイルサイズを削減。", icon: "✨", category: "デザイン" },
  { slug: "invoice-generator", name: "請求書作成", description: "ブラウザ上で請求書を作成してPDF出力。フリーランス・個人事業主に。", icon: "📄", category: "日常ツール" },
  { slug: "tip-calculator", name: "チップ計算", description: "食事代からチップ額と合計を計算。海外旅行・出張時に便利。", icon: "🍽️", category: "日常ツール" },
  { slug: "electricity-cost", name: "電気料金計算", description: "家電のW数と使用時間から電気料金を計算。節電の目安に。", icon: "⚡", category: "日常ツール" },
  { slug: "yaml-formatter", name: "YAML整形", description: "YAMLデータを見やすくフォーマット。インデントの自動修正と構文チェック。", icon: "📝", category: "開発ツール" },
  { slug: "toml-formatter", name: "TOML整形", description: "TOMLファイルを整形・検証。設定ファイルの編集に。", icon: "⚙️", category: "開発ツール" },
  { slug: "env-validator", name: ".env検証", description: ".envファイルの構文チェックと重複キーの検出。環境変数の管理に。", icon: "🔐", category: "開発ツール" },
  { slug: "http-header-viewer", name: "HTTPヘッダー確認", description: "URLのHTTPレスポンスヘッダーを一覧表示。キャッシュやセキュリティの確認に。", icon: "📡", category: "開発ツール" },
  { slug: "regex-cheatsheet", name: "正規表現チートシート", description: "よく使う正規表現パターンを一覧表示。クリックでコピー。", icon: "📋", category: "開発ツール" },
  { slug: "diff-checker", name: "テキスト差分比較（高機能）", description: "2つのテキストの差分を行単位・文字単位でハイライト表示。コードレビューに。", icon: "🔍", category: "開発ツール" },
  { slug: "markdown-preview", name: "Markdownプレビュー", description: "Markdownテキストをリアルタイムでプレビュー。README作成に便利。", icon: "📖", category: "開発ツール" },
  { slug: "wedding-cost", name: "結婚式費用計算", description: "ゲスト人数・料理・衣装から結婚式の概算費用をシミュレーション。", icon: "💒", category: "日常ツール" },
  { slug: "baby-name-generator", name: "名前候補生成", description: "画数や読みの条件から赤ちゃんの名前候補を生成。姓名判断の参考に。", icon: "👶", category: "日常ツール" },
  { slug: "moving-cost", name: "引越し費用計算", description: "距離・荷物量・時期から引越し費用の目安を計算。", icon: "🚚", category: "日常ツール" },
  { slug: "speed-converter", name: "速度変換", description: "km/h・mph・m/s・ノットを相互変換。", icon: "🏎️", category: "日常ツール" },
  { slug: "cooking-converter", name: "料理単位変換", description: "大さじ・小さじ・カップ・ml・gを相互変換。レシピの分量調整に。", icon: "🍳", category: "日常ツール" },
  { slug: "noise-generator", name: "ホワイトノイズ生成", description: "集中・睡眠用のホワイトノイズ・ピンクノイズをブラウザで再生。", icon: "🎧", category: "日常ツール" },
  { slug: "button-generator", name: "CSSボタン生成", description: "色・角丸・影・ホバーを調整してCSSボタンコードを生成。プレビュー付き。", icon: "🔘", category: "デザイン" },
  { slug: "text-shadow-generator", name: "テキストシャドウ生成", description: "CSSのtext-shadowをスライダーで視覚的に作成。コードをコピー。", icon: "💫", category: "デザイン" },
  { slug: "aspect-ratio-resizer", name: "画像リサイズ計算", description: "アスペクト比を維持したまま、幅または高さを指定してリサイズ後のサイズを計算。", icon: "📐", category: "画像・メディア" },
  { slug: "binary-calculator", name: "2進数計算機", description: "2進数同士の加算・減算・論理演算（AND/OR/XOR/NOT）を実行。", icon: "🔢", category: "開発ツール" },
  { slug: "blood-pressure", name: "血圧判定", description: "収縮期・拡張期の血圧値から血圧レベルを判定。WHO基準に基づく分類。", icon: "💓", category: "日常ツール" },
  { slug: "body-fat", name: "体脂肪率計算", description: "身長・体重・年齢・性別からBMI法で体脂肪率を推定。健康管理に。", icon: "⚖️", category: "日常ツール" },
  { slug: "button-css-generator", name: "ボタンCSS生成（高機能）", description: "Webボタンのデザインをビジュアルにカスタマイズ。CSSコードを即生成。", icon: "🎯", category: "デザイン" },
  { slug: "color-mix", name: "色混合ツール", description: "2つの色を混合して中間色を生成。混合比率も調整可能。", icon: "🎨", category: "デザイン" },
  { slug: "color-opacity", name: "色の透明度変換", description: "HEX・RGBカラーにアルファ値（透明度）を適用。rgba/hexa形式で出力。", icon: "🫧", category: "デザイン" },
  { slug: "color-wheel", name: "カラーホイール", description: "色相環から補色・類似色・トライアドなどの配色パターンを生成。", icon: "🌈", category: "デザイン" },
  { slug: "csp-generator", name: "CSPヘッダー生成", description: "Content-Security-Policyヘッダーをビジュアルに設定・生成。", icon: "🛡️", category: "開発ツール" },
  { slug: "css-filter-generator", name: "CSSフィルター生成", description: "blur・brightness・contrast等のCSSフィルターをプレビュー付きで設定。", icon: "🖼️", category: "デザイン" },
  { slug: "dpi-calculator", name: "DPI計算", description: "解像度・画面サイズからDPI(PPI)を計算。ディスプレイの精細さを確認。", icon: "🖥️", category: "デザイン" },
  { slug: "electricity-rate", name: "電気料金比較計算", description: "家電の消費電力と使用時間から月額・年額の電気代を計算。複数の家電を比較。", icon: "💡", category: "日常ツール" },
  { slug: "font-size-converter", name: "フォントサイズ変換", description: "px・pt・em・rem・%のフォントサイズを相互変換。", icon: "🔤", category: "デザイン" },
  { slug: "glassmorphism", name: "グラスモーフィズムCSS", description: "すりガラス風デザインのCSSを生成。透明度・ぼかし・色を調整。", icon: "🪟", category: "デザイン" },
  { slug: "grade-calculator", name: "成績計算", description: "テストの点数と配点から平均点・合計点・偏差値を計算。", icon: "📊", category: "日常ツール" },
  { slug: "html-entities", name: "HTMLエンティティ一覧", description: "よく使うHTMLエンティティ（特殊文字）の一覧表。クリックでコピー。", icon: "📝", category: "開発ツール" },
  { slug: "ip-subnet", name: "サブネット計算", description: "IPアドレスとCIDRプレフィックスからネットワーク情報を計算。", icon: "🌐", category: "開発ツール" },
  { slug: "json-escape", name: "JSONエスケープ", description: "JSON文字列のエスケープ・アンエスケープ。特殊文字の処理に。", icon: "🔧", category: "開発ツール" },
  { slug: "jwt-generator", name: "JWT生成・デコード", description: "ヘッダー・ペイロードからJWTトークンを生成。デコードも可能。", icon: "🔑", category: "セキュリティ" },
  { slug: "loan-calculator", name: "ローン返済計算", description: "借入額・金利・返済期間から月々の返済額と総返済額を計算。", icon: "🏦", category: "日常ツール" },
  { slug: "markdown-cheatsheet", name: "Markdownチートシート", description: "Markdown記法の早見表。構文と表示結果を並べて確認。", icon: "📋", category: "開発ツール" },
  { slug: "matrix-calculator", name: "行列計算", description: "2x2、3x3行列の加算・減算・乗算・行列式・転置・逆行列を計算。", icon: "🧮", category: "日常ツール" },
  { slug: "morse-code", name: "モールス信号変換", description: "テキストをモールス信号に変換、またはモールス信号をテキストに復元。", icon: "📡", category: "テキスト" },
  { slug: "nato-alphabet", name: "NATOフォネティックコード変換", description: "テキストをNATOフォネティックアルファベットに変換。電話での伝達に。", icon: "🗣️", category: "テキスト" },
  { slug: "neumorphism", name: "ニューモーフィズムCSS", description: "ニューモーフィズムデザインのCSSを生成。凹凸・影・色を調整。", icon: "🎛️", category: "デザイン" },
  { slug: "pace-calculator", name: "ランニングペース計算", description: "距離・タイムからペース(分/km)を計算。マラソン・ジョギングの記録管理に。", icon: "🏃", category: "日常ツール" },
  { slug: "paper-size", name: "用紙サイズ一覧", description: "A判・B判・はがき等の用紙サイズをmm/inch/pxで一覧表示。印刷に便利。", icon: "📄", category: "日常ツール" },
  { slug: "pregnancy-due-date", name: "出産予定日計算", description: "最終月経日から出産予定日を計算。妊娠週数・月数も表示。", icon: "🤰", category: "日常ツール" },
  { slug: "quadratic-equation", name: "二次方程式の解", description: "ax² + bx + c = 0 の係数を入力して解を求める。判別式・頂点座標も表示。", icon: "📈", category: "日常ツール" },
  { slug: "resolution-list", name: "画面解像度一覧", description: "主要なディスプレイ・デバイスの画面解像度を一覧表示。レスポンシブ設計に。", icon: "📱", category: "デザイン" },
  { slug: "romaji-converter", name: "ローマ字変換", description: "ひらがな・カタカナをヘボン式ローマ字に変換。", icon: "🔠", category: "テキスト" },
  { slug: "roman-numeral", name: "ローマ数字変換", description: "アラビア数字とローマ数字を相互に変換。", icon: "🏛️", category: "日常ツール" },
  { slug: "scrollbar-css", name: "スクロールバーCSS", description: "カスタムスクロールバーのCSSを生成。幅・色・角丸を設定。", icon: "📜", category: "デザイン" },
  { slug: "shoe-size", name: "靴サイズ変換", description: "日本・US・UK・EUの靴サイズを一覧で比較。", icon: "👟", category: "日常ツール" },
  { slug: "svg-preview", name: "SVGプレビュー", description: "SVGコードを貼り付けてリアルタイムでプレビュー表示。サイズ確認にも。", icon: "🖌️", category: "デザイン" },
  { slug: "svg-to-base64", name: "SVG→Base64変換", description: "SVGコードをBase64エンコードしたdata URIに変換。CSS背景画像等に。", icon: "🔄", category: "開発ツール" },
  { slug: "text-to-html", name: "テキスト→HTML変換", description: "プレーンテキストをHTMLに変換。改行をbrタグ、空行で段落をpタグに。URLを自動リンク化。", icon: "🏷️", category: "開発ツール" },
  { slug: "unit-price", name: "単価計算", description: "商品の価格と量から単価を計算し、お買い得商品を比較。", icon: "🛒", category: "日常ツール" },
  { slug: "url-builder", name: "URL構築ツール", description: "URLのパス・クエリパラメータ・フラグメントを視覚的に組み立て。UTMパラメータにも対応。", icon: "🔗", category: "開発ツール" },
  { slug: "text-to-speech-preview", name: "テキスト読み上げプレビュー", description: "ブラウザのWeb Speech APIでテキストを音声再生。読み上げ速度・声の種類を選択。", icon: "🔊", category: "テキスト" },
  { slug: "vertical-text-novel", name: "縦書き変換", description: "横書きテキストを縦書き表示に変換。小説・俳句の表示に。", icon: "📜", category: "テキスト" },
  { slug: "text-statistics", name: "テキスト統計分析", description: "文章の漢字率・ひらがな率・カタカナ率・平均文長を分析。", icon: "📊", category: "テキスト" },
  { slug: "furigana-generator", name: "ふりがな付与", description: "漢字にふりがな（ルビ）を自動付与。HTMLルビタグで出力。", icon: "🔤", category: "テキスト" },
  { slug: "text-to-table", name: "テキスト→表変換", description: "タブ区切り・カンマ区切りテキストを見やすい表に変換。", icon: "📊", category: "テキスト" },
  { slug: "palindrome-checker", name: "回文チェッカー", description: "入力した文が回文かどうかを判定。", icon: "🔁", category: "テキスト" },
  { slug: "text-reverse-advanced", name: "テキスト逆順変換", description: "文字列を逆順に変換。文字単位・単語単位を選択可能。", icon: "↩️", category: "テキスト" },
  { slug: "text-sort-lines", name: "行ソート", description: "テキストの行をアルファベット順・数値順・逆順にソート。", icon: "🔢", category: "テキスト" },
  { slug: "text-unique-lines", name: "重複行削除", description: "テキストから重複する行を削除。ユニークな行のみ残す。", icon: "✨", category: "テキスト" },
  { slug: "text-number-lines", name: "行番号付与", description: "テキストの各行に行番号を付与。開始番号・書式を指定可能。", icon: "🔢", category: "テキスト" },
  { slug: "text-wrap", name: "テキスト折り返し", description: "指定文字数で自動改行。メール文面の整形に。", icon: "📝", category: "テキスト" },
  { slug: "bracket-matcher", name: "括弧マッチチェック", description: "テキスト内の括弧（(){}[]）の対応を検証。", icon: "🔍", category: "テキスト" },
  { slug: "emoji-search-advanced", name: "絵文字検索", description: "キーワードで絵文字を検索。クリックでコピー。", icon: "😀", category: "テキスト" },
  { slug: "text-binary-converter", name: "テキスト⇔バイナリ変換", description: "テキストと2進数表現を相互変換。", icon: "💻", category: "テキスト" },
  { slug: "word-frequency-ranking", name: "単語出現頻度", description: "テキスト中の単語の出現回数をランキング表示。", icon: "📈", category: "テキスト" },
  { slug: "json-to-typescript-advanced", name: "JSON→TypeScript型変換", description: "JSONデータからTypeScriptのインターフェース定義を自動生成。", icon: "📝", category: "開発ツール" },
  { slug: "json-yaml-converter", name: "JSON⇔YAML変換", description: "JSONとYAML形式を相互変換。", icon: "🔄", category: "開発ツール" },
  { slug: "json-path-explorer", name: "JSONパスファインダー", description: "JSONデータのパスを視覚的に探索・コピー。", icon: "🗺️", category: "開発ツール" },
  { slug: "sql-format-advanced", name: "SQL整形", description: "SQL文を見やすくインデント・フォーマット。", icon: "🗃️", category: "開発ツール" },
  { slug: "cron-expression", name: "Cron式ビルダー", description: "Cron式を視覚的に組み立て。次回実行時刻も表示。", icon: "⏰", category: "開発ツール" },
  { slug: "http-status-reference", name: "HTTPステータスコード一覧", description: "ステータスコードの意味と説明を検索可能な一覧で表示。", icon: "📡", category: "開発ツール" },
  { slug: "css-minify-tool", name: "CSS圧縮", description: "CSSコードを圧縮（minify）して軽量化。", icon: "🗜️", category: "開発ツール" },
  { slug: "html-minifier", name: "HTML圧縮", description: "HTMLコードを圧縮してファイルサイズを削減。", icon: "🗜️", category: "開発ツール" },
  { slug: "js-minify-tool", name: "JavaScript圧縮", description: "JavaScriptコードを圧縮・難読化。", icon: "🗜️", category: "開発ツール" },
  { slug: "xml-format-tool", name: "XML整形", description: "XMLデータを見やすくインデント・フォーマット。", icon: "📄", category: "開発ツール" },
  { slug: "toml-to-json", name: "TOML⇔JSON変換", description: "TOML形式とJSON形式を相互変換。", icon: "🔄", category: "開発ツール" },
  { slug: "env-editor", name: ".env編集", description: "環境変数ファイル(.env)をGUIで編集。キーバリューペアの追加・削除。", icon: "📝", category: "開発ツール" },
  { slug: "api-tester", name: "APIテスター", description: "REST APIにリクエストを送信してレスポンスを確認。GET/POST/PUT/DELETE対応。", icon: "🌐", category: "開発ツール" },
  { slug: "curl-to-code", name: "cURL→コード変換", description: "cURLコマンドをPython・JavaScript・PHP等のコードに変換。", icon: "💻", category: "開発ツール" },
  { slug: "chmod-calc", name: "chmod計算機", description: "Linuxのファイルパーミッションを数値と記号で相互変換。", icon: "🔒", category: "開発ツール" },
  { slug: "docker-compose-validator", name: "Docker Compose検証", description: "docker-compose.ymlの構文チェック。", icon: "🐳", category: "開発ツール" },
  { slug: "git-command-builder", name: "Gitコマンドビルダー", description: "よく使うGitコマンドをGUIで組み立て。", icon: "🔀", category: "開発ツール" },
  { slug: "mime-type-lookup", name: "MIMEタイプ検索", description: "ファイル拡張子からMIMEタイプを検索、またはその逆。", icon: "📎", category: "開発ツール" },
  { slug: "htaccess-builder", name: ".htaccessジェネレーター", description: "リダイレクト・キャッシュ等の.htaccessルールをGUIで生成。", icon: "⚙️", category: "開発ツール" },
  { slug: "robots-txt-builder", name: "robots.txt生成", description: "robots.txtファイルをビジュアルに生成。", icon: "🤖", category: "開発ツール" },
  { slug: "image-placeholder", name: "プレースホルダー画像生成", description: "指定サイズ・色・テキストのダミー画像を生成。", icon: "🖼️", category: "画像・メディア" },
  { slug: "favicon-creator", name: "ファビコン生成", description: "テキストやアイコンからファビコン（.ico/.png）を生成。", icon: "⭐", category: "画像・メディア" },
  { slug: "image-compare-slider", name: "画像比較スライダー", description: "2枚の画像をスライダーで左右に比較表示。", icon: "🔀", category: "画像・メディア" },
  { slug: "image-base64-converter", name: "画像→Base64変換", description: "画像ファイルをBase64エンコードしたdata URIに変換。", icon: "🔄", category: "画像・メディア" },
  { slug: "color-picker-from-image", name: "画像からカラーピック", description: "画像をアップロードしてピクセルの色を取得。", icon: "🎨", category: "画像・メディア" },
  { slug: "image-metadata", name: "画像メタデータ表示", description: "JPEG/PNG画像のExif・メタ情報を表示。", icon: "ℹ️", category: "画像・メディア" },
  { slug: "image-crop-tool", name: "画像切り抜き", description: "画像を指定範囲で切り抜き。アスペクト比の固定にも対応。", icon: "✂️", category: "画像・メディア" },
  { slug: "image-rotate", name: "画像回転", description: "画像を90度単位または任意の角度で回転。", icon: "🔄", category: "画像・メディア" },
  { slug: "video-to-gif-guide", name: "動画→GIF変換ガイド", description: "動画からGIFアニメを作成する方法を解説。", icon: "🎬", category: "画像・メディア" },
  { slug: "audio-waveform", name: "音声波形表示", description: "音声ファイルの波形を視覚的に表示。", icon: "🎵", category: "画像・メディア" },
  { slug: "tax-calc-tool", name: "消費税計算", description: "税込み⇔税抜きの金額を計算。8%・10%対応。", icon: "💴", category: "日常ツール" },
  { slug: "tip-calc-tool", name: "チップ計算", description: "レストランのチップ額と割り勘を計算。", icon: "🍽️", category: "日常ツール" },
  { slug: "fuel-cost", name: "ガソリン代計算", description: "距離・燃費・ガソリン単価から交通費を計算。", icon: "⛽", category: "日常ツール" },
  { slug: "cooking-unit", name: "料理単位変換", description: "大さじ・小さじ・カップ・ml・gを相互変換。", icon: "🍳", category: "日常ツール" },
  { slug: "random-number-generator", name: "乱数生成", description: "範囲を指定してランダムな数値を生成。くじ引き・抽選に。", icon: "🎲", category: "日常ツール" },
  { slug: "countdown-timer-tool", name: "カウントダウンタイマー", description: "目標日時までの残り時間をリアルタイム表示。", icon: "⏳", category: "日常ツール" },
  { slug: "stopwatch-tool", name: "ストップウォッチ", description: "高精度なオンラインストップウォッチ。ラップタイム記録付き。", icon: "⏱️", category: "日常ツール" },
  { slug: "world-clock-tool", name: "世界時計", description: "世界各都市の現在時刻を一覧表示。複数都市を同時に確認。", icon: "🌍", category: "日常ツール" },
  { slug: "currency-converter-guide", name: "為替レート計算ガイド", description: "主要通貨の為替レートと換算方法を解説。", icon: "💱", category: "日常ツール" },
  { slug: "calorie-calc-tool", name: "カロリー計算", description: "基礎代謝量と1日の消費カロリーを計算。", icon: "🔥", category: "日常ツール" },
  { slug: "sleep-cycle-calculator", name: "睡眠時間計算", description: "起床時刻から最適な就寝時刻を計算（90分サイクル）。", icon: "😴", category: "日常ツール" },
  { slug: "blood-type-predict", name: "血液型予測", description: "両親の血液型から子供の血液型の確率を計算。", icon: "🩸", category: "日常ツール" },
  { slug: "clothing-size", name: "服サイズ変換", description: "日本・US・UK・EUの服サイズを変換。", icon: "👔", category: "日常ツール" },
  { slug: "zodiac-sign-calculator", name: "星座・干支計算", description: "生年月日から星座と干支を判定。", icon: "⭐", category: "日常ツール" },
  { slug: "japanese-era", name: "和暦西暦変換", description: "令和・平成・昭和・大正の和暦と西暦を相互変換。", icon: "🗾", category: "日常ツール" },
  { slug: "discount-calc-tool", name: "割引計算", description: "定価と割引率から割引後の価格を計算。", icon: "🏷️", category: "日常ツール" },
  { slug: "split-bill-tool", name: "割り勘計算", description: "合計金額と人数から一人あたりの金額を計算。端数調整あり。", icon: "🍻", category: "日常ツール" },
  { slug: "mortgage-calc-tool", name: "住宅ローン計算", description: "借入額・金利・期間から月々の返済額・総返済額を計算。", icon: "🏠", category: "日常ツール" },
  { slug: "savings-calc-tool", name: "貯金シミュレーション", description: "毎月の積立額と利率から将来の貯蓄額を計算。", icon: "💰", category: "日常ツール" },
  { slug: "speed-unit-tool", name: "速度変換", description: "km/h・mph・m/s・ノットを相互変換。", icon: "🏎️", category: "日常ツール" },
  { slug: "temperature-converter", name: "温度変換（詳細）", description: "摂氏・華氏・ケルビンを相互変換。計算式も表示。", icon: "🌡️", category: "日常ツール" },
  { slug: "area-calc-tool", name: "面積計算", description: "様々な図形（正方形・長方形・円・三角形等）の面積を計算。", icon: "📐", category: "日常ツール" },
  { slug: "volume-calc-tool", name: "体積計算", description: "立方体・球・円柱・円錐等の体積を計算。", icon: "📦", category: "日常ツール" },
  { slug: "percentage-calc-tool", name: "パーセント計算", description: "％の計算（割合・増減率・構成比）をまとめて実行。", icon: "💯", category: "日常ツール" },
  { slug: "power-calculator", name: "電力計算", description: "ワット数・アンペア・ボルトの相互変換。", icon: "⚡", category: "日常ツール" },
  { slug: "css-clip-path", name: "CSSクリップパス生成", description: "CSS clip-pathをビジュアルに編集。多角形・円・楕円に対応。", icon: "✂️", category: "デザイン" },
  { slug: "css-animation-generator", name: "CSSアニメーション生成", description: "キーフレームアニメーションをGUIで作成。", icon: "🎬", category: "デザイン" },
  { slug: "css-grid-generator", name: "CSSグリッド生成", description: "CSS Gridレイアウトをビジュアルに設計・コード生成。", icon: "🔲", category: "デザイン" },
  { slug: "css-flexbox-generator", name: "Flexboxビルダー", description: "Flexboxレイアウトをビジュアルに設計。各プロパティの効果をプレビュー。", icon: "📐", category: "デザイン" },
  { slug: "border-radius-generator", name: "border-radius生成", description: "四隅のborder-radiusを個別に設定。プレビュー付き。", icon: "⬜", category: "デザイン" },
  { slug: "text-shadow-tool", name: "テキストシャドウ生成", description: "text-shadowのCSS値をビジュアルに調整・生成。", icon: "💫", category: "デザイン" },
  { slug: "backdrop-filter", name: "バックドロップフィルター生成", description: "backdrop-filterのCSS値を設定。ぼかし・明度等を調整。", icon: "🪟", category: "デザイン" },
  { slug: "color-palette-generator", name: "カラーパレット生成", description: "ベースカラーから調和のとれた配色パレットを自動生成。", icon: "🎨", category: "デザイン" },
  { slug: "contrast-check-tool", name: "コントラスト比チェック", description: "2色のコントラスト比をWCAG基準で判定。アクセシビリティ確認に。", icon: "👁️", category: "デザイン" },
  { slug: "image-color-palette", name: "画像からパレット抽出", description: "画像の主要カラーを自動抽出してパレット化。", icon: "🖼️", category: "デザイン" },
  { slug: "css-transform-generator", name: "CSS Transform生成", description: "translate・rotate・scale・skewをプレビュー付きで設定。", icon: "🔄", category: "デザイン" },
  { slug: "responsive-font-calculator", name: "レスポンシブフォント計算", description: "clamp()を使ったレスポンシブフォントサイズを計算。", icon: "🔤", category: "デザイン" },
  { slug: "tailwind-converter", name: "Tailwind CSS変換", description: "通常のCSSをTailwindのクラス名に変換。", icon: "🌬️", category: "デザイン" },
  { slug: "svg-path-editor", name: "SVGパスエディター", description: "SVGのpath要素を視覚的に編集。", icon: "🖌️", category: "デザイン" },
  { slug: "icon-search", name: "アイコン検索", description: "人気のオープンソースアイコンをキーワード検索。SVG/CSSコードをコピー。", icon: "🔍", category: "デザイン" },
  { slug: "password-strength-checker", name: "パスワード強度チェック", description: "パスワードの強度を分析・スコア表示。改善提案も表示。", icon: "🛡️", category: "セキュリティ" },
  { slug: "encryption-tool", name: "テキスト暗号化", description: "AES暗号化でテキストを暗号化・復号化。", icon: "🔐", category: "セキュリティ" },
  { slug: "ssl-checker-guide", name: "SSL証明書確認ガイド", description: "SSL証明書の確認方法と有効期限チェックの手順を解説。", icon: "🔒", category: "セキュリティ" },
  { slug: "two-factor-guide", name: "二段階認証設定ガイド", description: "主要サービスの二段階認証の設定方法を解説。", icon: "🔑", category: "セキュリティ" },
  { slug: "privacy-checker", name: "プライバシー設定チェックリスト", description: "SNS・ブラウザのプライバシー設定を確認するチェックリスト。", icon: "🕵️", category: "セキュリティ" },
  { slug: "data-breach-guide", name: "情報漏洩確認ガイド", description: "メールアドレスの情報漏洩を確認する方法を解説。", icon: "⚠️", category: "セキュリティ" },
  { slug: "secure-delete-guide", name: "安全なデータ削除ガイド", description: "ファイルを完全に削除する方法を解説。", icon: "🗑️", category: "セキュリティ" },
  { slug: "vpn-speed-test-guide", name: "VPN速度テストガイド", description: "VPN接続時の速度を測定する方法を解説。", icon: "🌐", category: "セキュリティ" },
  { slug: "phishing-checker", name: "フィッシング判定ガイド", description: "怪しいメール・URLの見分け方を解説。チェックリスト付き。", icon: "🎣", category: "セキュリティ" },
  { slug: "cookie-consent-guide", name: "Cookie管理ガイド", description: "ブラウザのCookie設定と管理方法を解説。", icon: "🍪", category: "セキュリティ" },
  { slug: "fiber-fee-simulator", name: "光回線料金シミュレーター", description: "速度プラン・家族人数・スマホ割引から光回線の月額を試算。", icon: "🌐", category: "日常ツール" },
  { slug: "sim-fee-simulator", name: "格安SIM料金シミュレーター", description: "データ容量・通話オプション・家族回線数から月額コストを試算。", icon: "📱", category: "日常ツール" },
  { slug: "vpn-cost-simulator", name: "VPN料金シミュレーター", description: "契約期間・同時接続数から主要VPNの年間コストを比較。", icon: "🛡️", category: "セキュリティ" },
  { slug: "car-loan-simulator", name: "自動車ローンシミュレーター", description: "車両価格・頭金・金利・期間から月々の返済額と総返済額を試算。", icon: "🚗", category: "日常ツール" },
  { slug: "rent-budget-calculator", name: "家賃適正額計算ツール", description: "年収から無理のない適正家賃（手取りの25〜33%）を自動計算。", icon: "🏠", category: "日常ツール" },
  { slug: "education-cost-simulator", name: "教育費シミュレーター", description: "幼稚園から大学まで公立／私立別に累積教育費の目安を試算。", icon: "🎓", category: "日常ツール" },
  { slug: "retirement-savings-calculator", name: "老後資金シミュレーター", description: "現在年齢・目標額・想定利回りから必要な月額積立を自動計算。", icon: "👵", category: "日常ツール" },
  { slug: "insurance-need-calculator", name: "必要保障額計算ツール", description: "家族構成・収入・住宅ローンから生命保険の必要保障額を算出。", icon: "🛟", category: "日常ツール" },
  { slug: "freelance-tax-calculator", name: "フリーランス税金計算", description: "年収・経費から所得税・住民税・国民健康保険・国民年金の概算と手取りを試算。", icon: "💼", category: "日常ツール" },
  { slug: "side-business-tax-calculator", name: "副業バレない収入シミュレーター", description: "副業所得から確定申告の要否・住民税の追加額・バレ対策を判定。", icon: "🤫", category: "日常ツール" },
  { slug: "investment-fund-simulator", name: "積立投資シミュレーター", description: "毎月積立額・利回り・期間から複利運用後の将来資産をグラフ表示で試算。", icon: "📈", category: "日常ツール" },
  { slug: "smart-tax-saving-checker", name: "節税チェックリスト", description: "ふるさと納税・iDeCoなど所得控除を網羅チェック。節税ポテンシャルを可視化。", icon: "✅", category: "日常ツール" },
  { slug: "electricity-saving-calculator", name: "電気代節約シミュレーター", description: "家電別の使用時間から月間電気代と年間節約可能額を算出。", icon: "💡", category: "日常ツール" },
  { slug: "bmi-detail-calculator", name: "BMI詳細計算（体脂肪率・基礎代謝・必要カロリー）", description: "BMIに加え体脂肪率・基礎代謝・1日の必要カロリーをまとめて算出。", icon: "🏋️", category: "日常ツール" },
  { slug: "work-hour-calculator", name: "労働時間・残業代計算", description: "出退勤時刻・休憩・賃金から労働時間と残業代（割増率込み）を自動計算。", icon: "⏰", category: "日常ツール" },
  { slug: "age-in-detail-calculator", name: "年齢詳細計算（和暦・干支・星座）", description: "生年月日から満年齢・数え年・和暦・干支・星座・誕生日までの日数を表示。", icon: "🎂", category: "日常ツール" },
  { slug: "password-strength-tester", name: "パスワード強度テスター", description: "リアルタイムでパスワードの強度・エントロピー・推定解析時間を評価。", icon: "🛡️", category: "セキュリティ" },
  { slug: "url-shortener-info", name: "URL短縮サービス比較", description: "Bitly・TinyURL・is.gd等の特徴を比較。各公式サービスへワンクリックで誘導。", icon: "🔗", category: "開発ツール" },
  { slug: "furusato-tax-simulator", name: "ふるさと納税限度額シミュレーター", description: "年収・家族構成から自己負担2,000円で済む寄付上限額の目安を試算。", icon: "🎁", category: "日常ツール" },
  { slug: "ideco-simulator", name: "iDeCoシミュレーター", description: "毎月積立額・年収・職業区分から、年間節税額と将来資産を試算。", icon: "🏦", category: "日常ツール" },
  { slug: "inheritance-tax-simulator", name: "相続税シミュレーター", description: "資産総額・法定相続人数から相続税の基礎控除額と概算税額を試算。", icon: "📜", category: "日常ツール" },
  { slug: "company-savings-simulator", name: "企業型DCシミュレーター", description: "会社拠出＋マッチング拠出による確定拠出年金の将来資産と節税額を試算。", icon: "🏢", category: "日常ツール" },
  { slug: "tax-bracket-calculator", name: "所得税ブラケット計算", description: "年収から課税所得・適用税率・所得税・住民税の概算を表示。", icon: "📊", category: "日常ツール" },
  { slug: "invoice-tax-calculator", name: "インボイス税額計算", description: "適格請求書発行事業者・非適格事業者との取引における消費税の仕入税額控除差額を計算。経過措置にも対応。", icon: "🧾", category: "日常ツール" },
  { slug: "withholding-tax-calculator", name: "源泉徴収税額計算", description: "報酬・料金等から源泉徴収すべき所得税額を自動計算。原稿料・司法書士報酬・配当金など複数パターンに対応。", icon: "💼", category: "日常ツール" },
  { slug: "vat-calculator", name: "消費税計算（内税・外税対応）", description: "税抜⇔税込の双方向変換に対応した消費税計算ツール。標準税率10%・軽減税率8%対応。", icon: "💴", category: "日常ツール" },
  { slug: "business-trip-allowance-calculator", name: "出張旅費・日当計算", description: "役職・国内外・日数・宿泊数から日当と宿泊費の合計を計算。旅費規程の整備や経費精算に。", icon: "✈️", category: "日常ツール" },
  { slug: "annual-leave-calculator", name: "有給休暇付与日数計算", description: "労働基準法に基づき勤続年数と週の所定労働日数から年次有給休暇の付与日数を計算。", icon: "📅", category: "日常ツール" },
  { slug: "wedding-cost-detail-simulator", name: "結婚式費用詳細シミュレーター", description: "招待人数・地域・挙式スタイルから結婚式の総費用・内訳・自己負担額を詳細に試算。", icon: "💒", category: "日常ツール" },
  { slug: "child-allowance-simulator", name: "児童手当受給額シミュレーター", description: "子供の年齢・人数から児童手当の月額・年額・累計受給額を試算。2024年拡充後の最新制度対応。", icon: "👶", category: "日常ツール" },
  { slug: "birth-cost-simulator", name: "出産費用シミュレーター", description: "分娩方法・入院日数・部屋タイプから出産費用を試算。出産育児一時金50万円の差引後自己負担も表示。", icon: "🤱", category: "日常ツール" },
  { slug: "moving-cost-detail-simulator", name: "引越し費用詳細見積もり", description: "荷物量・距離・時期から引越し費用の概算と見積もりレンジを算出。繁忙期/閑散期の料金差も確認。", icon: "📦", category: "日常ツール" },
  { slug: "car-expense-yearly-calculator", name: "自動車年間維持費計算", description: "自動車税・任意保険・車検・燃料費・駐車場代から年間・月額維持費を一括試算。", icon: "🚗", category: "日常ツール" },
];

export const siteConfig = {
  name: "ネットツールボックス",
  description: "無料で使えるWeb便利ツール集。QRコード作成、文字数カウント、パスワード生成など、日常で使えるツールが揃っています。",
  url: "https://net-toolbox.jp",
};
