export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: string;
}

export const tools: Tool[] = [
  {
    slug: "qr-code",
    name: "QRコード作成",
    description: "テキストやURLからQRコードを簡単に作成。PNG画像としてダウンロードできます。",
    icon: "📱",
    category: "画像・メディア",
  },
  {
    slug: "character-count",
    name: "文字数カウント",
    description: "文章の文字数・単語数・行数をリアルタイムでカウント。レポートやSNS投稿に便利。",
    icon: "🔢",
    category: "テキスト",
  },
  {
    slug: "password-generator",
    name: "パスワード生成",
    description: "安全なランダムパスワードを生成。長さや使用文字を自由にカスタマイズ。",
    icon: "🔐",
    category: "セキュリティ",
  },
  {
    slug: "json-formatter",
    name: "JSON整形",
    description: "JSONデータを見やすくフォーマット。構文チェックも同時に行います。",
    icon: "📋",
    category: "開発ツール",
  },
  {
    slug: "color-converter",
    name: "カラーコード変換",
    description: "HEX・RGB・HSLのカラーコードを相互変換。プレビュー付きで色を確認。",
    icon: "🎨",
    category: "デザイン",
  },
  {
    slug: "base64",
    name: "Base64変換",
    description: "テキストをBase64にエンコード・デコード。日本語テキストにも対応。",
    icon: "🔄",
    category: "開発ツール",
  },
  {
    slug: "url-encode",
    name: "URLエンコード/デコード",
    description: "URLの日本語や特殊文字をパーセントエンコーディング形式に変換・復元。",
    icon: "🔗",
    category: "開発ツール",
  },
  {
    slug: "date-calculator",
    name: "日数計算",
    description: "2つの日付間の日数を計算。何日後・何日前の日付も求められます。",
    icon: "📅",
    category: "日常ツール",
  },
  {
    slug: "text-diff",
    name: "テキスト差分比較",
    description: "2つのテキストを比較して差分をハイライト表示。変更箇所を素早く確認。",
    icon: "📝",
    category: "テキスト",
  },
  {
    slug: "hash-generator",
    name: "ハッシュ生成",
    description: "SHA-1/SHA-256/SHA-512のハッシュ値を生成。データ整合性の確認に。",
    icon: "🛡️",
    category: "セキュリティ",
  },
  {
    slug: "fullwidth-halfwidth",
    name: "全角半角変換",
    description: "全角⇔半角の英数字変換、ひらがな⇔カタカナ変換に対応。",
    icon: "🔠",
    category: "テキスト",
  },
  {
    slug: "age-calculator",
    name: "年齢計算",
    description: "生年月日から年齢・生まれてからの日数・次の誕生日までを計算。",
    icon: "🎂",
    category: "日常ツール",
  },
  {
    slug: "unit-converter",
    name: "単位変換",
    description: "長さ・重さ・温度の単位を相互変換。cm/inch/kg/lbなど対応。",
    icon: "📏",
    category: "日常ツール",
  },
  {
    slug: "markdown-preview",
    name: "マークダウンプレビュー",
    description: "マークダウン記法をリアルタイムでHTMLプレビュー表示。",
    icon: "✍️",
    category: "開発ツール",
  },
  {
    slug: "html-escape",
    name: "HTMLエスケープ",
    description: "HTMLの特殊文字をエスケープ・アンエスケープ。XSS対策に。",
    icon: "🏷️",
    category: "開発ツール",
  },
  {
    slug: "csv-json",
    name: "CSV⇔JSON変換",
    description: "CSVデータをJSON形式に、JSONをCSV形式に相互変換。",
    icon: "📊",
    category: "開発ツール",
  },
  {
    slug: "regex-tester",
    name: "正規表現テスト",
    description: "正規表現パターンをリアルタイムでテスト。マッチ結果を即確認。",
    icon: "🔍",
    category: "開発ツール",
  },
  {
    slug: "text-replace",
    name: "テキスト置換",
    description: "テキスト内の文字列を一括検索・置換。正規表現にも対応。",
    icon: "🔃",
    category: "テキスト",
  },
  {
    slug: "dummy-text",
    name: "ダミーテキスト生成",
    description: "Webデザイン・モックアップ用の日本語ダミーテキストを生成。",
    icon: "📄",
    category: "テキスト",
  },
  {
    slug: "radix-converter",
    name: "進数変換",
    description: "2進数・8進数・10進数・16進数を相互変換。",
    icon: "🔢",
    category: "開発ツール",
  },
  {
    slug: "timestamp-converter",
    name: "タイムスタンプ変換",
    description: "Unixタイムスタンプと日時を相互変換。現在時刻も表示。",
    icon: "⏱️",
    category: "開発ツール",
  },
  {
    slug: "aspect-ratio",
    name: "アスペクト比計算",
    description: "画面の幅と高さからアスペクト比を計算。動画・画像サイズに。",
    icon: "🖥️",
    category: "デザイン",
  },
  {
    slug: "case-converter",
    name: "大文字小文字変換",
    description: "UPPER/lower/Title/camelCase/snake_case/kebab-caseに変換。",
    icon: "🔤",
    category: "テキスト",
  },
  {
    slug: "uuid-generator",
    name: "UUID生成",
    description: "ランダムなUUID（v4）を一括生成。最大100個まで。",
    icon: "🆔",
    category: "開発ツール",
  },
  {
    slug: "bmi-calculator",
    name: "BMI計算",
    description: "身長と体重からBMI（体格指数）を計算。肥満度を判定。",
    icon: "⚖️",
    category: "日常ツール",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum生成",
    description: "英語のLorem Ipsumダミーテキストを段落数指定で生成。",
    icon: "📜",
    category: "テキスト",
  },
  {
    slug: "reading-time",
    name: "読了時間計算",
    description: "文章の読了時間を推定。日本語・英語の両方に対応。",
    icon: "⏳",
    category: "テキスト",
  },
  {
    slug: "mortgage-calculator",
    name: "住宅ローン計算",
    description: "借入額・金利・年数から月々の返済額と総返済額を計算。",
    icon: "🏠",
    category: "日常ツール",
  },
  {
    slug: "ip-info",
    name: "IPアドレス確認",
    description: "自分のIPアドレス・端末情報・ブラウザ情報を確認。",
    icon: "🌐",
    category: "開発ツール",
  },
  {
    slug: "word-counter-en",
    name: "英語ワードカウンター",
    description: "英文の単語数・文数・段落数を計測。頻出単語も表示。",
    icon: "🔠",
    category: "テキスト",
  },
  {
    slug: "tax-calculator",
    name: "消費税計算",
    description: "税込・税抜価格を簡単計算。軽減税率8%にも対応。",
    icon: "🧾",
    category: "日常ツール",
  },
  {
    slug: "discount-calculator",
    name: "割引計算",
    description: "割引額・割引率を計算。セール価格の確認に便利。",
    icon: "🏷️",
    category: "日常ツール",
  },
  {
    slug: "random-number",
    name: "乱数生成",
    description: "指定範囲のランダムな数字を生成。複数同時生成も可能。",
    icon: "🎲",
    category: "日常ツール",
  },
  {
    slug: "text-sort",
    name: "テキスト行ソート",
    description: "テキストの行を昇順・降順・数値順に並べ替え。",
    icon: "📶",
    category: "テキスト",
  },
  {
    slug: "duplicate-remover",
    name: "重複行削除",
    description: "テキストの重複行を除去。大文字小文字の区別も選択可能。",
    icon: "🗑️",
    category: "テキスト",
  },
  {
    slug: "wareki-converter",
    name: "和暦西暦変換",
    description: "令和・平成・昭和・大正・明治を西暦に相互変換。",
    icon: "🗓️",
    category: "日常ツール",
  },
  {
    slug: "world-clock",
    name: "世界時計",
    description: "世界各地の現在時刻をリアルタイムで表示。時差確認に。",
    icon: "🕐",
    category: "日常ツール",
  },
  {
    slug: "number-formatter",
    name: "数字フォーマット",
    description: "数値をカンマ区切り・漢数字（万/億）・通貨形式に変換。",
    icon: "💹",
    category: "日常ツール",
  },
  {
    slug: "lottery",
    name: "抽選ツール",
    description: "リストからランダムに当選者を選出。抽選アニメーション付き。",
    icon: "🎯",
    category: "日常ツール",
  },
  {
    slug: "text-reverse",
    name: "テキスト反転",
    description: "文字列・単語・行の順序を反転。3つのモードに対応。",
    icon: "🔁",
    category: "テキスト",
  },
  {
    slug: "json-yaml",
    name: "JSON⇔YAML変換",
    description: "JSONとYAMLを相互変換。設定ファイルの形式変更に。",
    icon: "📑",
    category: "開発ツール",
  },
  {
    slug: "cron-parser",
    name: "Cron式解説",
    description: "Cronスケジュールを日本語で解説。次回実行時刻も表示。",
    icon: "⏰",
    category: "開発ツール",
  },
  {
    slug: "byte-counter",
    name: "バイト数計算",
    description: "テキストのバイト数をUTF-8/UTF-16等で計測。",
    icon: "📐",
    category: "開発ツール",
  },
  {
    slug: "color-names",
    name: "HTMLカラー名一覧",
    description: "CSS/HTMLカラー名とコードを検索。127色対応。",
    icon: "🌈",
    category: "デザイン",
  },
  {
    slug: "calculator",
    name: "電卓",
    description: "オンライン計算機。四則演算・パーセント計算に対応。",
    icon: "🔢",
    category: "日常ツール",
  },
  {
    slug: "percentage-calculator",
    name: "パーセント計算",
    description: "割合・百分率を3つのモードで計算。増減率にも対応。",
    icon: "📊",
    category: "日常ツール",
  },
  {
    slug: "countdown",
    name: "カウントダウン",
    description: "目標日までの残り時間をリアルタイムで表示。",
    icon: "⏳",
    category: "日常ツール",
  },
  {
    slug: "text-encrypt",
    name: "テキスト暗号化",
    description: "ROT13・シーザー暗号・XORで簡易暗号化・復号化。",
    icon: "🔒",
    category: "セキュリティ",
  },
  {
    slug: "image-resize",
    name: "画像リサイズ",
    description: "画像のサイズを変更。アスペクト比維持・形式変換対応。",
    icon: "🖼️",
    category: "画像・メディア",
  },
  {
    slug: "qr-reader",
    name: "画像情報確認",
    description: "画像のサイズ・形式・ファイルサイズを確認。",
    icon: "📷",
    category: "画像・メディア",
  },
  { slug: "weekday-calculator", name: "曜日計算", description: "特定の日付の曜日を調べる。和暦表示にも対応。", icon: "📆", category: "日常ツール" },
  { slug: "zodiac-calculator", name: "干支計算", description: "生まれ年から十二支（干支）を調べる。", icon: "🐉", category: "日常ツール" },
  { slug: "horoscope-calculator", name: "星座計算", description: "誕生日から12星座を調べる。", icon: "⭐", category: "日常ツール" },
  { slug: "time-calculator", name: "時間計算", description: "時間の足し算・引き算。時分秒を計算。", icon: "⏱️", category: "日常ツール" },
  { slug: "speed-calculator", name: "速度計算", description: "距離・時間・速度を相互計算。", icon: "🚗", category: "日常ツール" },
  { slug: "electricity-calculator", name: "電気料金計算", description: "電化製品の月間・年間電気代を計算。", icon: "💡", category: "日常ツール" },
  { slug: "calorie-calculator", name: "基礎代謝計算", description: "年齢・性別・体格から1日の消費カロリーを計算。", icon: "🔥", category: "日常ツール" },
  { slug: "fuel-calculator", name: "燃費計算", description: "走行距離と給油量から燃費を計算。", icon: "⛽", category: "日常ツール" },
  { slug: "area-calculator", name: "面積計算", description: "円・長方形・三角形・台形の面積を計算。", icon: "📐", category: "日常ツール" },
  { slug: "volume-calculator", name: "体積計算", description: "直方体・球・円柱・円錐の体積を計算。", icon: "📦", category: "日常ツール" },
  { slug: "line-number", name: "行番号付与", description: "テキストの各行に行番号を追加。", icon: "🔢", category: "テキスト" },
  { slug: "html-strip", name: "HTMLタグ除去", description: "HTMLからタグを除去してテキストを抽出。", icon: "🧹", category: "テキスト" },
  { slug: "newline-converter", name: "改行コード変換", description: "CRLF/LF/CRの改行コードを相互変換。", icon: "↩️", category: "テキスト" },
  { slug: "indent-converter", name: "インデント変換", description: "タブ⇔スペースのインデントを変換。", icon: "➡️", category: "テキスト" },
  { slug: "text-similarity", name: "テキスト類似度", description: "2つの文章の類似度をパーセントで表示。", icon: "🔬", category: "テキスト" },
  { slug: "random-string", name: "ランダム文字列生成", description: "ランダムな文字列を指定条件で生成。", icon: "🎰", category: "開発ツール" },
  { slug: "char-code", name: "文字コード確認", description: "文字のUnicode・UTF-8コードを確認。", icon: "🔣", category: "開発ツール" },
  { slug: "unicode-search", name: "Unicode文字検索", description: "Unicode文字を名前やコードで検索・コピー。", icon: "🔎", category: "開発ツール" },
  { slug: "emoji-list", name: "絵文字一覧", description: "カテゴリ別の絵文字を検索・コピー。130種以上。", icon: "😀", category: "テキスト" },
  { slug: "text-binary", name: "テキスト⇔バイナリ", description: "文字列を2進数に変換・復元。", icon: "🔀", category: "開発ツール" },
  { slug: "sql-formatter", name: "SQLフォーマッター", description: "SQLクエリを見やすく整形。", icon: "🗃️", category: "開発ツール" },
  { slug: "css-formatter", name: "CSSフォーマッター", description: "CSSコードを見やすく整形・圧縮。", icon: "🎨", category: "開発ツール" },
  { slug: "xml-formatter", name: "XML整形", description: "XMLデータを見やすくフォーマット。", icon: "📰", category: "開発ツール" },
  { slug: "http-status-codes", name: "HTTPステータスコード一覧", description: "60以上のHTTPステータスコードを検索。", icon: "🌐", category: "開発ツール" },
  { slug: "keycode-checker", name: "キーコード確認", description: "キーボードのキーコードをリアルタイム表示。", icon: "⌨️", category: "開発ツール" },
  { slug: "useragent-parser", name: "UserAgent解析", description: "ブラウザ・OS・デバイス情報を解析。", icon: "🕵️", category: "開発ツール" },
  { slug: "css-unit-converter", name: "CSS単位変換", description: "px/rem/em/ptを相互変換。", icon: "📏", category: "開発ツール" },
  { slug: "css-gradient", name: "CSSグラデーション生成", description: "グラデーションCSSコードを視覚的に生成。", icon: "🌈", category: "デザイン" },
  { slug: "css-box-shadow", name: "CSSボックスシャドウ生成", description: "box-shadowをスライダーで視覚的に生成。", icon: "🖼️", category: "デザイン" },
  { slug: "htaccess-generator", name: ".htaccess生成", description: "リダイレクトやアクセス制御の.htaccessを生成。", icon: "⚙️", category: "開発ツール" },
  { slug: "random-color", name: "ランダムカラー生成", description: "ランダムな色をHEX/RGB/HSLで生成。", icon: "🎨", category: "デザイン" },
  { slug: "color-palette", name: "カラーパレット生成", description: "ベースカラーから配色パレットを自動生成。", icon: "🖌️", category: "デザイン" },
  { slug: "font-preview", name: "フォントプレビュー", description: "テキストを様々なフォントで比較プレビュー。", icon: "🔤", category: "デザイン" },
  { slug: "ogp-size-list", name: "OGP画像サイズ一覧", description: "SNS別のOGP推奨画像サイズを一覧表示。", icon: "📱", category: "デザイン" },
  { slug: "favicon-preview", name: "ファビコンプレビュー", description: "テキストや絵文字からファビコンをプレビュー。", icon: "🔖", category: "デザイン" },
  { slug: "barcode-generator", name: "バーコード生成", description: "テキストからCode128バーコードを生成。", icon: "📊", category: "画像・メディア" },
  { slug: "contrast-checker", name: "コントラスト比チェック", description: "WCAG基準で色のアクセシビリティを確認。", icon: "👁️", category: "デザイン" },
  { slug: "pixel-cm-converter", name: "ピクセル⇔cm変換", description: "DPI指定でpx/cm/mm/inchを相互変換。", icon: "📐", category: "デザイン" },
  { slug: "passphrase-generator", name: "パスフレーズ生成", description: "覚えやすい日本語パスフレーズを生成。", icon: "🔑", category: "セキュリティ" },
  { slug: "data-url", name: "データURL変換", description: "テキストをデータURI形式に変換。", icon: "🔗", category: "開発ツール" },
  { slug: "password-strength", name: "パスワード強度チェック", description: "パスワードの安全性をエントロピーで診断。", icon: "🛡️", category: "セキュリティ" },
  { slug: "port-list", name: "ポート番号一覧", description: "よく使われるTCP/UDPポート番号を検索。", icon: "🔌", category: "開発ツール" },
  { slug: "regex-cheatsheet", name: "正規表現チートシート", description: "正規表現の書き方をカテゴリ別に一覧表示。", icon: "📖", category: "開発ツール" },
  { slug: "keyboard-shortcuts", name: "ショートカットキー一覧", description: "Windows/Macのキーボードショートカット集。", icon: "⌨️", category: "開発ツール" },
  { slug: "sns-char-limit", name: "SNS文字数制限チェック", description: "各SNSの文字数制限をリアルタイム確認。", icon: "📱", category: "テキスト" },
  { slug: "sitemap-generator", name: "サイトマップ生成", description: "URLリストからXMLサイトマップを作成。", icon: "🗺️", category: "開発ツール" },
  { slug: "meta-tag-generator", name: "メタタグ生成", description: "SEO用メタタグ・OGPタグを自動生成。", icon: "🏷️", category: "開発ツール" },
  { slug: "robots-txt-generator", name: "robots.txt生成", description: "robots.txtをオプション選択で簡単作成。", icon: "🤖", category: "開発ツール" },
  { slug: "json-path-finder", name: "JSONパス検索", description: "JSONのキーをクリックしてパスを取得。", icon: "🔍", category: "開発ツール" },
  { slug: "markdown-table", name: "マークダウンテーブル生成", description: "表形式のデータからMarkdown表を作成。", icon: "📊", category: "開発ツール" },
  { slug: "compound-interest", name: "複利計算", description: "元金・金利・期間から複利で増える金額を計算。", icon: "💰", category: "日常ツール" },
  { slug: "savings-calculator", name: "積立計算", description: "毎月の積立額から将来の資産を計算。", icon: "🏦", category: "日常ツール" },
  { slug: "currency-converter", name: "為替換算", description: "主要通貨を日本円に換算。10通貨対応。", icon: "💱", category: "日常ツール" },
  { slug: "salary-calculator", name: "給与手取り計算", description: "年収から手取り額を概算。", icon: "💼", category: "日常ツール" },
  { slug: "split-bill", name: "割り勘計算", description: "合計金額と人数から一人あたりの支払額を計算。", icon: "🍻", category: "日常ツール" },
  { slug: "profit-calculator", name: "利益率計算", description: "売上と原価から利益率を計算。", icon: "📈", category: "日常ツール" },
  { slug: "roi-calculator", name: "ROI計算", description: "投資額と収益から投資収益率を計算。", icon: "📊", category: "日常ツール" },
  { slug: "breakeven-calculator", name: "損益分岐点計算", description: "固定費・変動費から損益分岐点を計算。", icon: "⚖️", category: "日常ツール" },
  { slug: "ideal-weight", name: "適正体重計算", description: "身長から適正体重を複数の計算式で算出。", icon: "🏃", category: "日常ツール" },
  { slug: "water-intake", name: "水分摂取量計算", description: "体重と活動量から1日の必要水分量を計算。", icon: "💧", category: "日常ツール" },
  { slug: "sleep-calculator", name: "睡眠時間計算", description: "起床時刻から理想の就寝時刻を計算。", icon: "😴", category: "日常ツール" },
  { slug: "dog-age-calculator", name: "犬の年齢計算", description: "犬の年齢を人間に換算。", icon: "🐕", category: "日常ツール" },
  { slug: "timer", name: "タイマー", description: "カウントダウンタイマー。アラーム付き。", icon: "⏲️", category: "日常ツール" },
  { slug: "stopwatch", name: "ストップウォッチ", description: "経過時間を計測。ラップタイム対応。", icon: "⏱️", category: "日常ツール" },
  { slug: "pomodoro-timer", name: "ポモドーロタイマー", description: "25分集中+5分休憩の作業タイマー。", icon: "🍅", category: "日常ツール" },
  { slug: "gcd-lcm", name: "最大公約数・最小公倍数", description: "2つ以上の数のGCD・LCMを計算。", icon: "🔢", category: "日常ツール" },
  { slug: "prime-checker", name: "素数判定", description: "数値が素数かどうかを判定。素因数分解も。", icon: "🔬", category: "日常ツール" },
  { slug: "factorial", name: "階乗計算", description: "階乗・順列・組み合わせを計算。", icon: "❗", category: "日常ツール" },
  { slug: "fibonacci", name: "フィボナッチ数列", description: "フィボナッチ数列を指定項数まで生成。", icon: "🌀", category: "日常ツール" },
  { slug: "trigonometry", name: "三角関数計算", description: "sin/cos/tan等の三角関数を計算。", icon: "📐", category: "日常ツール" },
  { slug: "logarithm", name: "対数計算", description: "常用対数・自然対数・任意底の対数を計算。", icon: "📈", category: "日常ツール" },
  { slug: "statistics", name: "統計計算", description: "平均・中央値・標準偏差等の統計値を計算。", icon: "📊", category: "日常ツール" },
  { slug: "probability", name: "確率計算", description: "順列・組み合わせ・確率を計算。", icon: "🎲", category: "日常ツール" },
  { slug: "vertical-text", name: "縦書き変換", description: "テキストを縦書き表示に変換。", icon: "📜", category: "テキスト" },
  { slug: "halfwidth-katakana", name: "半角カタカナ変換", description: "全角⇔半角カタカナを変換。濁点対応。", icon: "🔤", category: "テキスト" },
  { slug: "text-split", name: "テキスト分割", description: "区切り文字でテキストを分割。", icon: "✂️", category: "テキスト" },
  { slug: "csv-viewer", name: "CSVビューアー", description: "CSVデータを表形式で見やすく表示。", icon: "📋", category: "開発ツール" },
  { slug: "tsv-csv-converter", name: "TSV⇔CSV変換", description: "タブ区切り⇔カンマ区切りを変換。", icon: "🔄", category: "開発ツール" },
  { slug: "json-minify", name: "JSON圧縮", description: "JSONを最小化して容量を削減。", icon: "📦", category: "開発ツール" },
  { slug: "word-frequency", name: "単語頻度分析", description: "テキストの出現単語をランキング表示。", icon: "📊", category: "テキスト" },
  { slug: "css-animation", name: "CSSアニメーション生成", description: "CSSアニメーションを視覚的に生成。", icon: "🎬", category: "デザイン" },
  { slug: "css-flexbox", name: "CSS Flexbox", description: "Flexboxレイアウトを視覚的に確認。", icon: "📐", category: "デザイン" },
  { slug: "css-grid", name: "CSS Grid", description: "Gridレイアウトを視覚的に確認。", icon: "🔲", category: "デザイン" },
  { slug: "url-parser", name: "URLパーサー", description: "URLの構成要素を分解して表示。", icon: "🔗", category: "開発ツール" },
  { slug: "cookie-viewer", name: "Cookie確認", description: "ブラウザのCookieを一覧表示。", icon: "🍪", category: "開発ツール" },
  { slug: "localstorage-viewer", name: "LocalStorage確認", description: "ブラウザのLocalStorageを管理。", icon: "💾", category: "開発ツール" },
  { slug: "responsive-tester", name: "レスポンシブテスター", description: "各画面サイズでのサイト表示を確認。", icon: "📱", category: "開発ツール" },
  { slug: "image-base64", name: "画像Base64変換", description: "画像をBase64データURLに変換。", icon: "🖼️", category: "画像・メディア" },
  { slug: "screen-size", name: "画面サイズ確認", description: "画面・ウィンドウのサイズをリアルタイム表示。", icon: "🖥️", category: "開発ツール" },
  { slug: "video-size-calculator", name: "動画容量計算", description: "解像度・ビットレートから動画容量を見積もり。", icon: "🎥", category: "画像・メディア" },
  { slug: "audio-bitrate", name: "音声ビットレート計算", description: "音声ファイルの容量をビットレートから計算。", icon: "🎵", category: "画像・メディア" },
  { slug: "image-size-estimator", name: "画像容量見積もり", description: "画像のファイルサイズを解像度から推定。", icon: "📸", category: "画像・メディア" },
  { slug: "data-size-converter", name: "データ容量変換", description: "B/KB/MB/GB/TBを相互変換。", icon: "💿", category: "開発ツール" },
  { slug: "speed-unit-converter", name: "速度単位変換", description: "km/h・mph・m/s・ノットを変換。", icon: "🏎️", category: "日常ツール" },
  { slug: "angle-converter", name: "角度変換", description: "度・ラジアン・グラジアンを変換。", icon: "📐", category: "日常ツール" },
  { slug: "title-checker", name: "タイトルタグチェッカー", description: "SEOタイトルの長さとSERP表示を確認。", icon: "🏷️", category: "開発ツール" },
  { slug: "meta-description-checker", name: "メタディスクリプションチェッカー", description: "SEO説明文の長さをチェック。", icon: "📝", category: "開発ツール" },
  { slug: "keyword-density", name: "キーワード密度計算", description: "テキスト内のキーワード出現率を計算。", icon: "🔑", category: "開発ツール" },
  { slug: "heading-checker", name: "見出し構造チェッカー", description: "HTML見出しの階層構造を確認。", icon: "📑", category: "開発ツール" },
  { slug: "google-preview", name: "Google検索結果プレビュー", description: "SERPでの表示をプレビュー。", icon: "🔍", category: "開発ツール" },
  { slug: "og-preview", name: "OGPプレビュー", description: "SNSシェア時のOGP表示を確認。", icon: "📱", category: "開発ツール" },
  { slug: "twitter-preview", name: "Twitter Cardプレビュー", description: "X/Twitterでのカード表示を確認。", icon: "🐦", category: "開発ツール" },
  { slug: "jsonld-generator", name: "構造化データ生成", description: "JSON-LD構造化データを作成。", icon: "🏗️", category: "開発ツール" },
  { slug: "breadcrumb-generator", name: "パンくずリスト生成", description: "パンくずのHTML/JSON-LDを作成。", icon: "🍞", category: "開発ツール" },
  { slug: "gitignore-generator", name: ".gitignore生成", description: "言語別の.gitignoreファイルを作成。", icon: "📁", category: "開発ツール" },
  { slug: "readme-generator", name: "README生成", description: "README.mdテンプレートを作成。", icon: "📖", category: "開発ツール" },
  { slug: "license-generator", name: "ライセンス生成", description: "MIT/Apache/GPL等のライセンスを作成。", icon: "⚖️", category: "開発ツール" },
  { slug: "ip-converter", name: "IPアドレス変換", description: "IPを2進数・16進数・整数に変換。", icon: "🌐", category: "開発ツール" },
  { slug: "mac-formatter", name: "MACアドレスフォーマッター", description: "MACアドレスを各種形式に整形。", icon: "🔌", category: "開発ツール" },
  { slug: "jwt-decoder", name: "JWTデコーダー", description: "JWTトークンのヘッダー・ペイロードを解析。", icon: "🔓", category: "開発ツール" },
  { slug: "crontab-generator", name: "Crontab生成", description: "cronスケジュールを視覚的に作成。", icon: "⏰", category: "開発ツール" },
  { slug: "docker-template", name: "Dockerfileテンプレート", description: "Dockerfileを簡単に生成。", icon: "🐳", category: "開発ツール" },
  { slug: "random-name", name: "ランダム名前生成", description: "ダミーの日本人名を生成。", icon: "👤", category: "日常ツール" },
  { slug: "dice", name: "サイコロ", description: "オンラインダイスロール。多面体対応。", icon: "🎲", category: "日常ツール" },
  { slug: "janken", name: "じゃんけん", description: "コンピュータとじゃんけん対戦。", icon: "✊", category: "日常ツール" },
  { slug: "typing-test", name: "タイピング速度テスト", description: "タイピング速度を計測。", icon: "⌨️", category: "日常ツール" },
  { slug: "reaction-test", name: "反応速度テスト", description: "反応速度をミリ秒で計測。", icon: "⚡", category: "日常ツール" },
  { slug: "memory-test", name: "記憶力テスト", description: "数字の記憶力をテスト。", icon: "🧠", category: "日常ツール" },
  { slug: "notepad", name: "メモ帳", description: "ブラウザで使えるオンラインメモ帳。自動保存。", icon: "📝", category: "日常ツール" },
  { slug: "todo-list", name: "TODOリスト", description: "ブラウザで使えるタスク管理ツール。", icon: "✅", category: "日常ツール" },
  { slug: "checklist-generator", name: "チェックリスト生成", description: "チェックリストを作成・印刷。", icon: "☑️", category: "日常ツール" },
  { slug: "color-blindness", name: "色覚シミュレーション", description: "色覚異常での色の見え方を確認。", icon: "👁️", category: "デザイン" },
  { slug: "emoji-converter", name: "顔文字⇔絵文字変換", description: "顔文字と絵文字を相互変換。", icon: "😊", category: "テキスト" },
  { slug: "placeholder-image", name: "プレースホルダー画像", description: "ダミー画像URLを指定サイズで生成。", icon: "🖼️", category: "デザイン" },
  { slug: "gradient-text", name: "グラデーション文字", description: "グラデーション文字のCSSを生成。", icon: "🌈", category: "デザイン" },
  { slug: "border-radius", name: "border-radius生成", description: "角丸CSSを視覚的に生成。", icon: "⬜", category: "デザイン" },
  { slug: "text-to-speech", name: "テキスト読み上げ", description: "ブラウザでテキストを音声再生。", icon: "🔊", category: "日常ツール" },
  { slug: "aspect-ratio-list", name: "アスペクト比一覧", description: "よく使われる画面比率と解像度の一覧。", icon: "🖥️", category: "デザイン" },
  { slug: "encoding-detector", name: "文字化け修復", description: "文字化けしたテキストの修復を試みる。", icon: "🔧", category: "テキスト" },
  { slug: "what-day", name: "○日後計算", description: "指定日数後の日付を計算。", icon: "📅", category: "日常ツール" },
  { slug: "json-diff", name: "JSON差分比較", description: "2つのJSONの違いを比較。", icon: "🔍", category: "開発ツール" },
  { slug: "regex-generator", name: "正規表現パターン集", description: "よく使う正規表現パターンをコピー。", icon: "📋", category: "開発ツール" },
  { slug: "html-table", name: "HTMLテーブル生成", description: "HTML表を視覚的に作成。", icon: "📊", category: "開発ツール" },
  { slug: "char-diff", name: "文字レベル差分", description: "文字単位の差分をハイライト表示。", icon: "🔬", category: "テキスト" },
  { slug: "word-counter-jp", name: "日本語文字種カウンター", description: "漢字・ひらがな・カタカナの内訳を表示。", icon: "🔢", category: "テキスト" },
  { slug: "color-picker", name: "カラーピッカー", description: "HSLスライダーで直感的に色を選択。", icon: "🎨", category: "デザイン" },
  { slug: "whitespace-remover", name: "空白除去", description: "余分な空白・空行を一括削除。", icon: "🧹", category: "テキスト" },
  { slug: "number-to-kanji", name: "数字⇔漢数字変換", description: "数字を漢数字（一二三/壱弐参）に変換。", icon: "🔢", category: "日常ツール" },
  { slug: "epoch-converter", name: "エポック秒変換", description: "Unixエポックミリ秒⇔日時を変換。", icon: "⏰", category: "開発ツール" },
  { slug: "privacy-generator", name: "プライバシーポリシー生成", description: "個人情報保護方針テンプレートを作成。", icon: "🔒", category: "開発ツール" },
  { slug: "terms-generator", name: "利用規約生成", description: "利用規約テンプレートを作成。", icon: "📜", category: "開発ツール" },
  { slug: "slug-generator", name: "スラッグ生成", description: "URL用スラッグを自動生成。", icon: "🔗", category: "開発ツール" },
  { slug: "qr-bulk", name: "QRコード一括生成", description: "複数のQRコードを一度に生成。", icon: "📱", category: "画像・メディア" },
  { slug: "password-list", name: "パスワード一括生成", description: "複数のパスワードを一度に生成。", icon: "🔐", category: "セキュリティ" },
  { slug: "aspect-resizer", name: "アスペクト比リサイズ計算", description: "目標比率に合わせたサイズを計算。", icon: "📏", category: "デザイン" },
  { slug: "presentation-timer", name: "プレゼンタイマー", description: "プレゼンの残り時間を大画面表示。", icon: "🎤", category: "日常ツール" },
  { slug: "date-formatter", name: "日付フォーマット", description: "日付を10種類の形式で表示。", icon: "📅", category: "日常ツール" },
  { slug: "lorem-jp", name: "日本語ダミーテキスト（名文）", description: "名作文学からサンプル文を生成。", icon: "📚", category: "テキスト" },
  { slug: "cidr-calculator", name: "CIDRサブネット計算", description: "IPサブネットの範囲・ホスト数を計算。", icon: "🌐", category: "開発ツール" },
  { slug: "interview-timer", name: "面接タイマー", description: "面接の時間配分をステージ別に管理。", icon: "🤝", category: "日常ツール" },
];

export const siteConfig = {
  name: "ネットツールボックス",
  description: "無料で使えるWeb便利ツール集。QRコード作成、文字数カウント、パスワード生成など、日常で使えるツールが揃っています。",
  url: "https://net-toolbox.jp",
};
