"use client";

import { useState } from "react";
import Link from "next/link";
import { RelatedTools } from "@/components/RelatedTools";

interface Config {
  forceHttps: boolean;
  forceWww: boolean;
  removeWww: boolean;
  customRedirects: { from: string; to: string; code: "301" | "302" }[];
  denyAccess: string[];
  custom404: string;
  disableDirListing: boolean;
  cacheControl: boolean;
  gzipCompression: boolean;
  blockHotlinking: boolean;
  hotlinkDomain: string;
}

export default function HtaccessGeneratorPage() {
  const [config, setConfig] = useState<Config>({
    forceHttps: false,
    forceWww: false,
    removeWww: false,
    customRedirects: [],
    denyAccess: [],
    custom404: "",
    disableDirListing: false,
    cacheControl: false,
    gzipCompression: false,
    blockHotlinking: false,
    hotlinkDomain: "",
  });
  const [denyInput, setDenyInput] = useState("");
  const [copied, setCopied] = useState(false);

  const update = <K extends keyof Config>(key: K, value: Config[K]) => {
    setConfig((prev) => ({ ...prev, [key]: value }));
  };

  const addRedirect = () => {
    update("customRedirects", [
      ...config.customRedirects,
      { from: "", to: "", code: "301" },
    ]);
  };

  const updateRedirect = (
    index: number,
    field: keyof Config["customRedirects"][0],
    value: string
  ) => {
    update(
      "customRedirects",
      config.customRedirects.map((r, i) =>
        i === index ? { ...r, [field]: value } : r
      )
    );
  };

  const removeRedirect = (index: number) => {
    update(
      "customRedirects",
      config.customRedirects.filter((_, i) => i !== index)
    );
  };

  const addDenyPath = () => {
    if (!denyInput.trim()) return;
    update("denyAccess", [...config.denyAccess, denyInput.trim()]);
    setDenyInput("");
  };

  const removeDenyPath = (index: number) => {
    update("denyAccess", config.denyAccess.filter((_, i) => i !== index));
  };

  const generateCode = (): string => {
    const lines: string[] = [];

    lines.push("# Generated by htaccess Generator Tool");
    lines.push("");

    if (config.disableDirListing) {
      lines.push("# ディレクトリ一覧を無効化");
      lines.push("Options -Indexes");
      lines.push("");
    }

    if (config.forceHttps || config.forceWww || config.removeWww) {
      lines.push("RewriteEngine On");
      lines.push("");
    }

    if (config.forceHttps) {
      lines.push("# HTTPSを強制");
      lines.push("RewriteCond %{HTTPS} off");
      lines.push("RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    if (config.forceWww && !config.removeWww) {
      lines.push("# www あり に強制リダイレクト");
      lines.push("RewriteCond %{HTTP_HOST} !^www\\. [NC]");
      lines.push("RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    if (config.removeWww && !config.forceWww) {
      lines.push("# www なし に強制リダイレクト");
      lines.push("RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]");
      lines.push("RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]");
      lines.push("");
    }

    if (config.customRedirects.length > 0) {
      lines.push("# カスタムリダイレクト");
      config.customRedirects.forEach((r) => {
        if (r.from && r.to) {
          lines.push(`Redirect ${r.code} ${r.from} ${r.to}`);
        }
      });
      lines.push("");
    }

    if (config.denyAccess.length > 0) {
      lines.push("# アクセス制限");
      config.denyAccess.forEach((path) => {
        lines.push(`<Files "${path}">`);
        lines.push("  Require all denied");
        lines.push("</Files>");
      });
      lines.push("");
    }

    if (config.custom404) {
      lines.push("# カスタム404ページ");
      lines.push(`ErrorDocument 404 ${config.custom404}`);
      lines.push("");
    }

    if (config.cacheControl) {
      lines.push("# ブラウザキャッシュ設定");
      lines.push("<IfModule mod_expires.c>");
      lines.push("  ExpiresActive On");
      lines.push("  ExpiresByType image/jpg \"access plus 1 year\"");
      lines.push("  ExpiresByType image/jpeg \"access plus 1 year\"");
      lines.push("  ExpiresByType image/png \"access plus 1 year\"");
      lines.push("  ExpiresByType image/gif \"access plus 1 year\"");
      lines.push("  ExpiresByType image/webp \"access plus 1 year\"");
      lines.push("  ExpiresByType text/css \"access plus 1 month\"");
      lines.push("  ExpiresByType application/javascript \"access plus 1 month\"");
      lines.push("</IfModule>");
      lines.push("");
    }

    if (config.gzipCompression) {
      lines.push("# Gzip圧縮を有効化");
      lines.push("<IfModule mod_deflate.c>");
      lines.push("  AddOutputFilterByType DEFLATE text/html text/plain text/xml");
      lines.push("  AddOutputFilterByType DEFLATE text/css application/javascript");
      lines.push("  AddOutputFilterByType DEFLATE application/json application/xml");
      lines.push("</IfModule>");
      lines.push("");
    }

    if (config.blockHotlinking && config.hotlinkDomain) {
      lines.push("# 画像ホットリンク禁止");
      lines.push("RewriteEngine On");
      lines.push(`RewriteCond %{HTTP_REFERER} !^$`);
      lines.push(`RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${config.hotlinkDomain.replace(".", "\\.")} [NC]`);
      lines.push("RewriteRule \\.(jpg|jpeg|png|gif|webp)$ - [F,NC,L]");
      lines.push("");
    }

    return lines.join("\n").trim();
  };

  const code = generateCode();

  const copy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const CheckBox = ({
    label,
    checked,
    onChange,
  }: {
    label: string;
    checked: boolean;
    onChange: (v: boolean) => void;
  }) => (
    <label className="flex items-center gap-3 cursor-pointer py-2">
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className="w-4 h-4 rounded"
      />
      <span className="text-sm">{label}</span>
    </label>
  );

  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <nav className="text-sm text-muted mb-6">
        <Link href="/" className="hover:text-primary">トップ</Link>
        <span className="mx-2">/</span>
        <span>.htaccess生成</span>
      </nav>

      <h1 className="text-2xl font-bold mb-2">.htaccess生成ツール</h1>
      <p className="text-muted mb-8">
        .htaccessファイルのコードを自動生成します。HTTPSの強制・リダイレクト・アクセス制限・Gzip圧縮などのルールを選択してコードを生成してください。
      </p>

      <div className="bg-card-bg border border-card-border rounded-xl p-6 mb-6 space-y-6">

        {/* Basic settings */}
        <div>
          <h2 className="text-sm font-bold mb-2 text-muted uppercase tracking-wide">基本設定</h2>
          <div className="divide-y divide-card-border">
            <CheckBox label="HTTPSを強制（HTTP→HTTPSリダイレクト）" checked={config.forceHttps} onChange={(v) => update("forceHttps", v)} />
            <CheckBox label="www あり に統一（non-www → www）" checked={config.forceWww} onChange={(v) => { update("forceWww", v); if (v) update("removeWww", false); }} />
            <CheckBox label="www なし に統一（www → non-www）" checked={config.removeWww} onChange={(v) => { update("removeWww", v); if (v) update("forceWww", false); }} />
            <CheckBox label="ディレクトリ一覧を無効化（Options -Indexes）" checked={config.disableDirListing} onChange={(v) => update("disableDirListing", v)} />
          </div>
        </div>

        {/* Performance */}
        <div>
          <h2 className="text-sm font-bold mb-2 text-muted uppercase tracking-wide">パフォーマンス</h2>
          <div className="divide-y divide-card-border">
            <CheckBox label="ブラウザキャッシュを有効化（mod_expires）" checked={config.cacheControl} onChange={(v) => update("cacheControl", v)} />
            <CheckBox label="Gzip圧縮を有効化（mod_deflate）" checked={config.gzipCompression} onChange={(v) => update("gzipCompression", v)} />
          </div>
        </div>

        {/* Custom 404 */}
        <div>
          <h2 className="text-sm font-bold mb-2 text-muted uppercase tracking-wide">カスタム404ページ</h2>
          <input
            type="text"
            value={config.custom404}
            onChange={(e) => update("custom404", e.target.value)}
            placeholder="/404.html"
            className="w-full border border-card-border rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary bg-background"
          />
        </div>

        {/* Custom redirects */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <h2 className="text-sm font-bold text-muted uppercase tracking-wide">カスタムリダイレクト</h2>
            <button onClick={addRedirect} className="text-sm text-primary hover:text-primary-hover font-medium">+ 追加</button>
          </div>
          {config.customRedirects.length === 0 && (
            <p className="text-xs text-muted">「追加」ボタンでリダイレクトルールを追加できます。</p>
          )}
          <div className="space-y-2">
            {config.customRedirects.map((r, i) => (
              <div key={i} className="flex gap-2 items-center">
                <input
                  value={r.from}
                  onChange={(e) => updateRedirect(i, "from", e.target.value)}
                  placeholder="/old-page"
                  className="flex-1 border border-card-border rounded px-3 py-2 text-sm font-mono bg-background"
                />
                <span className="text-muted">→</span>
                <input
                  value={r.to}
                  onChange={(e) => updateRedirect(i, "to", e.target.value)}
                  placeholder="https://example.com/new-page"
                  className="flex-1 border border-card-border rounded px-3 py-2 text-sm font-mono bg-background"
                />
                <select
                  value={r.code}
                  onChange={(e) => updateRedirect(i, "code", e.target.value as "301" | "302")}
                  className="border border-card-border rounded px-2 py-2 text-sm bg-background"
                >
                  <option value="301">301</option>
                  <option value="302">302</option>
                </select>
                <button onClick={() => removeRedirect(i)} className="text-red-400 hover:text-red-600">×</button>
              </div>
            ))}
          </div>
        </div>

        {/* Deny access */}
        <div>
          <h2 className="text-sm font-bold mb-2 text-muted uppercase tracking-wide">アクセス制限（ファイル名）</h2>
          <div className="flex gap-2 mb-2">
            <input
              value={denyInput}
              onChange={(e) => setDenyInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && addDenyPath()}
              placeholder=".env, config.php など"
              className="flex-1 border border-card-border rounded-lg px-3 py-2 text-sm font-mono bg-background"
            />
            <button
              onClick={addDenyPath}
              className="bg-primary text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-primary-hover transition-colors"
            >
              追加
            </button>
          </div>
          <div className="flex flex-wrap gap-2">
            {config.denyAccess.map((path, i) => (
              <span key={i} className="flex items-center gap-1 bg-background border border-card-border rounded px-2 py-1 text-xs font-mono">
                {path}
                <button onClick={() => removeDenyPath(i)} className="text-red-400 hover:text-red-600 ml-1">×</button>
              </span>
            ))}
          </div>
        </div>

        {/* Hotlinking */}
        <div>
          <h2 className="text-sm font-bold mb-2 text-muted uppercase tracking-wide">画像ホットリンク禁止</h2>
          <CheckBox label="画像ホットリンクを禁止する" checked={config.blockHotlinking} onChange={(v) => update("blockHotlinking", v)} />
          {config.blockHotlinking && (
            <input
              type="text"
              value={config.hotlinkDomain}
              onChange={(e) => update("hotlinkDomain", e.target.value)}
              placeholder="example.com"
              className="w-full border border-card-border rounded-lg px-3 py-2 text-sm font-mono mt-2 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary bg-background"
            />
          )}
        </div>
      </div>

      {/* Output */}
      <div className="bg-card-bg border border-card-border rounded-xl p-6">
        <div className="flex items-center justify-between mb-3">
          <span className="text-sm font-bold">生成された .htaccess</span>
          <button
            onClick={copy}
            className="text-sm text-primary hover:text-primary-hover font-medium"
          >
            {copied ? "コピー済み" : "コピー"}
          </button>
        </div>
        <pre className="bg-background rounded-lg p-4 text-sm font-mono overflow-x-auto max-h-96 overflow-y-auto whitespace-pre-wrap">
          {code || "# オプションを選択するとコードが生成されます"}
        </pre>
      </div>

      <section className="mt-10">
        <h2 className="text-lg font-bold mb-3">.htaccess生成ツールの使い方</h2>
        <div className="text-sm text-muted leading-relaxed space-y-2">
          <p>1. 必要なオプション（HTTPS強制・リダイレクトなど）をチェック・設定します。</p>
          <p>2. 設定に応じて.htaccessのコードがリアルタイムで生成されます。</p>
          <p>3. 「コピー」ボタンでコードをコピーし、サーバーの.htaccessファイルに貼り付けます。</p>
          <p>.htaccessはApache Webサーバーの設定ファイルです。設定を変更するとサイトの動作に影響するため、バックアップを取ってから適用してください。</p>
        </div>
      </section>


      <RelatedTools currentSlug="htaccess-generator" category="開発ツール" />
    </div>
  );
}
